### ISSUE TITLE
Подготовка презентации для предзащиты

### ISSUE THREAD

**Issue by igsha** [13Fire13nyu/MasterDegree#11]
Ориентировочный объём презентации 20 слайдов.
Разделы презентации:
* Актуальность исследования (1 слайд)
* Цель исследования (1 слайд)
* Обзор существующих методов по теме диссертации (2-3 слайда)
* Общая схема получения основной гармоники (1 слайд)
* Расписывание всех этапов из схемы
* Приведение графиков обучения моделей
* Сравнение повышения точности при разных подходах (просто спектр, мел-спектр)
* Определение оптимальных параметров системы (борьба с переобучением, поиск размера окна для спектрограммы, шаг окон, количество фреймов, подаваемых на вход сети)
* Описание демострационного примера с результатами
* Выводы и дальнейшие исследования

Презентацию выкладывать на гитхаб к коду либо ссылку сюда на онлай-документ (GoogleDocs). Формат можно использовать pptx.

**Comment by 13Fire13nyu** [comment]
> Ориентировочный объём презентации 20 слайдов. Разделы презентации:
> 
> * Актуальность исследования (1 слайд)
> * Цель исследования (1 слайд)
> * Обзор существующих методов по теме диссертации (2-3 слайда)
> * Общая схема получения основной гармоники (1 слайд)
> * Расписывание всех этапов из схемы
> * Приведение графиков обучения моделей
> * Сравнение повышения точности при разных подходах (просто спектр, мел-спектр)
> * Определение оптимальных параметров системы (борьба с переобучением, поиск размера окна для спектрограммы, шаг окон, количество фреймов, подаваемых на вход сети)
> * Описание демострационного примера с результатами
> 
> Презентацию выкладывать на гитхаб к коду. Формат можно использовать pptx.

1. Под общей схемой подразумевается модель, предложенная в диссертации Ф. Корзениовски? 
2. Актуальность - это теперь применения, о которых я писала? 
3. Цель исследования - получение набора гармоник мелодии?

**Comment by igsha** [comment]
1. Общая схема - это то, что Вы делаете в своей диссертации.
2. Да, можно про применения. Но обычно под актуальностью понимают насколько сейчас это востребовано. На нашей стороне популярность каких-нибудь шазамов и высокие вычислительные мощности.
3. Напишите что-то в презентации, чтобы я мог подкорректировать. Сейчас этот вопросов очень неконкретный.

**Comment by 13Fire13nyu** [comment]
Залила частичную презентацию с текстом без последних трех пунктов плана.

**Comment by igsha** [comment]
Слайд №1: Моя должность на кафедре - старший преподаватель.
Слайд №2: Shazam не распознаёт ноты. Он делает сопоставление мелодий.
Слайды №№4-5: Можно привести только одну архитектуру для примера. Приведите список распространённых слоёв. Ещё покажите, что для классификации используется выбор максимального от softmax. На этих слайдах нужно подробнее показать как устроена классификация, как она выходит из регресии. Потому что мы потом классификацией занимаемся.
Слайд №12: Нужно показать формулу accuracy. Давайте называть мел-кепстр, а не мел-спектр.
Слайд №13: Расхождение декодирования индексов и нот со слайдом №9 (сраните таблицу 1 и 2).
Слайды №№14-15: Приведите сколько по времени обучаются модели и сколько времени тратится на предсказание. Может ещё тут можно вытащить выгоду.

**Comment by 13Fire13nyu** [comment]
> Слайд №1: Моя должность на кафедре - старший преподаватель. Слайд №2: Shazam не распознаёт ноты. Он делает сопоставление мелодий. Слайды №№4-5: Можно привести только одну архитектуру для примера. Приведите список распространённых слоёв. Ещё покажите, что для классификации используется выбор максимального от softmax. На этих слайдах нужно подробнее показать как устроена классификация, как она выходит из регресии. Потому что мы потом классификацией занимаемся. Слайд №12: Нужно показать формулу accuracy. Давайте называть мел-кепстр, а не мел-спектр. Слайд №13: Расхождение декодирования индексов и нот со слайдом №9 (сраните таблицу 1 и 2). Слайды №№14-15: Приведите сколько по времени обучаются модели и сколько времени тратится на предсказание. Может ещё тут можно вытащить выгоду.

Различие таблиц - это мне известно, но я не знаю, как это поправить, потому что ноты считываются именно так. Я потому и привожу 2 разные таблицы.

**Comment by igsha** [comment]
Вы же понимаете, что это ошибка где-то в коде? Её нужно исправить.

**Comment by 13Fire13nyu** [comment]
Добавила в презентацию и тексте к ней корректировки

**Comment by igsha** [comment]
Нужно добавить демонстрационный пример.

**Comment by 13Fire13nyu** [comment]
Добавила демонстрационные примеры для обоих методов, но что-то для второго метода довольно низкая точность.

**Comment by igsha** [comment]
Хорошо. Теперь презентация выглядит более-менее полно. Нужно завершать исследования и начинать параллельно писать текст диссертации.

**Comment by 13Fire13nyu** [comment]
Как можно объяснить, что дальше идут исследования именно второй модели, а не первой?

**Comment by igsha** [comment]
> Как можно объяснить, что дальше идут исследования именно второй модели, а не первой?

Обрабатывать данные 15x1025 или 15x40 будет быстрее? Это и есть ответ. Кстати, для мел-кепстра можно больше эпох использовать. Возможно и догонит точности.

**Comment by 13Fire13nyu** [comment]
> > Как можно объяснить, что дальше идут исследования именно второй модели, а не первой?
> 
> Обрабатывать данные 15x1025 или 15x40 будет быстрее? Это и есть ответ. Кстати, для мел-кепстра можно больше эпох использовать. Возможно и догонит точности.

Я пробовала увеличивать эпохи (когда пробовала регуляризацию), но это если и помогало, то в единичных случаях.

**Comment by 13Fire13nyu** [comment]
Пробовала рассмотреть модели при разных эпохах (брала значения 10, 50, 75, 100, 300, 500). Хотела сделать через кросс-валидацию, но для первой модели компьютер начал висеть, один раз даже выдал ошибку, что не может выделить определенное количество памяти. По второму методу пока не пробовала кросс-валидацию.

**Comment by igsha** [comment]
Можно просто взять много эпох и построить валидационную кривую постфакту. Затем смотреть, на какой эпохе уже были хорошие результаты.

**Comment by igsha** [comment]
Создам другую задачу для презентации. Её можно делать позже.
