### ISSUE TITLE
Оптимальные параметры: шаг окон и количество фреймов

### ISSUE THREAD

**Issue by igsha** [13Fire13nyu/MasterDegree#12]
Необходимо рассмотреть разные шаги окна и выяснить, насколько это влияет на точность. Одновременно с этим меняется количество фреймов, подаваемых на вход нейросети (сейчас это 15). Нужно делать больше и меньше и смотреть результаты. Возможно удастся уменьшить количество фреймов и ускорить вычисления.

Проводить исследования параметров по схеме кросс-валидации. Вывести список параметров и точности на этих параметрах.

Напомню схему кросс-валидации:
* Случайно выбираем данные (поддатасет) из датасета несколько раз (KFold)
* Делим полученные поддатасет на обучаемый и валидационный
* Обучаем нейросеть, проверяем на валидации
* Пересоздаём нейросеть заново и снова обучаем на других поддатасетах
* Выбираем те параметры, на которых валидационные метрики показали самые высокие результаты

Можете делать всё руками, но есть уже готовое решение `sklearn.cross_val_score` и `tensorflow.keras.wrappers.scikit_learn.KerasClassifier`: https://stackoverflow.com/a/57775402.

**Comment by 13Fire13nyu** [comment]
Как можно использовать кросс-валидацию, если параметры спектрограммы задаются отдельной функцией?

**Comment by igsha** [comment]
Эта база данных всё портит. Вы можете с самого начала сформировать все спектры, а потом эти данные подавать в сеть.

**Comment by 13Fire13nyu** [comment]
> Эта база данных всё портит. Вы можете с самого начала сформировать все спектры, а потом эти данные подавать в сеть.

Тогда остаётся вопрос с кросс-валидацией параметров спектрограммы, потому что они задаются внутри функции создания спектрограммы, а не функции создания модели.

**Comment by 13Fire13nyu** [comment]
Мне внести использование функции получения спектрограммы в функцию создания модели? Просто тогда изначальными X_train и X_test тогда будут сами звуковые сигналы, но входные данные должны быть одинакового размера

**Comment by igsha** [comment]
Тогда перебирайте параметры в цикле руками. Но в каждой итерации пересоздавайте модель. Выберите ту модель, которая показывает наилучшие результаты при валидации.

Я создам отдельную задачу на реализацию слоя препроцессинга.

**Comment by igsha** [comment]
Запомните, как Вы подбирали оптимальные параметры. Нам потом снова понадобится это сделать.
