### ISSUE TITLE
Слой предобработки

### ISSUE THREAD

**Issue by igsha** [13Fire13nyu/MasterDegree#14]
# Мотивация

Отправлять в модель данные и метки. Модель сама должна получать спектрограмму.

# Риски

Подход сильно коррелирует с процедурой нарезки файла для демонстрации.

# Теоретическое описание подхода

На вход сети подаются данные `(x, y)`, где `x` - это данные формата `data[N]`, взятые напрямую из аудиофайла, а `y` - это метка данных (нота). Сама сеть принимает не `data[N]`, а мел-кепстр размера `[M, 40]`. Слой предобработки строит кратковременное преобразование Фурье, получает мал-кепстр размера `[K, 40]`, а затем:
* если `K < M`, слой дополняет данные путём копирования до размера `[M, 40]`;
* если `K > M`, тогда слой выбирает случайно окно `[M, 40]` из `K - M + 1` вариантов;
* если `K = M`, то слой просто пробрасывает данные дальше.
В конечном итоге на вход сети всегда подаётся мел-кепстр размера `[M, 40]`.

# Практическая реализация

Реализация основана на слое `tf.keras.layers.Lambda`. Этот слой можно использовать как для обучения, так и для тестирования.

Слой производит преобразование `data[N] -> data[M, 40]`. Параметр `M` задаётся пользователем, размер `N` заранее неизвестен.
Этапы работы слоя:
* получение данных `data[N]`;
* преобразование `tf.signal.stft` с параметрами окна `K` и шага `S`. Получение матрицы `data[M, K // 2 + 1]`, где `M = floor(N / S`, либо `M = ceil(N / S)` - это решает сама функция, ничего считать не нужно руками;
* последовательные преобразования `log(abs(data) ** 2 / K)`;
* умножение на триангулярные фильтры `data @ fbank`, получение размерности `data[P, 40]`;
* если `P < M`, тогда `data = extent(data, data[-1])` - копирование последней строки до размера `M`;
* если `P > M`, тогда вычислить случайную первую строку `start = random(0, P - M)` и `data = data[start:start+M]`.

**Comment by 13Fire13nyu** [comment]
> 

Мне изначальные данные - аудиосигнал подавать надо как параметр функции, задающей сеть? Потому что я попыталась так сделать:
```
def create_model_1(waveform,S,M):
    x = layers.Lambda(get_spectrogram, name = "get_spectrogram")((waveform,S,M)) 
    inputs = layers.Input(shape = (x.shape[1],x.shape[2]), name = "inputs")
    x = layers.Flatten()(inputs)
    x = layers.Dense(512, activation = 'relu',
                     name = "relu_1")(x)
    x = layers.Dense(512, activation = 'relu',
                     name = "relu_2")(x)
    x = layers.Dense(512, activation = 'relu',
                     name = "relu_3")(x)
    outputs = layers.Dense(12,activation = 'softmax', name = "dense_end")(x)
    model = tf.keras.Model(inputs = inputs, outputs = outputs)
    model.compile(optimizer='adam',
                  loss = 'sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model
```
Потом я задала сетку параметров:
```
epochs = 100
step = list(map(int,[2048/32, 2048/16, 2048/8, 2048/4, 2048/2, 2048]))
num_frame = [5,10,15,20,25,30]
param_grid = dict(waveform = X_train, S = step, M = num_frame)
print(param_grid)
```
```
model = KerasClassifier(build_fn=create_model_1, epochs = 100, batch_size = 64)
kfold = RepeatedKFold(n_splits=5, n_repeats=5)
grid = GridSearchCV(model, param_grid=param_grid, cv=kfold)
history = grid.fit(X_train, y_train)
```
Но после запуска всего этого началась куча ошибок.

**Comment by 13Fire13nyu** [comment]
Моя функция получения спектрограммы сейчас выглядит так:
```
def get_spectrogram(params):
    waveform = params[0]
    S = params[1]
    M = params[2]
    K = 2048
    waveform = tf.cast(waveform, tf.float32)
    spectrogram = tf.signal.stft(waveform, frame_length=K, frame_step=S, pad_end=True)
    pow_frames = (1.0 / K) * ((tf.abs(spectrogram)) ** 2)
    pow_frames = tf.where(pow_frames == 0, tf.keras.backend.epsilon(), pow_frames)  # Численная стабильность 
    # tf.keras.backend.epsilon() - машинный ноль)
    spectrogram = tf.tensordot(pow_frames, fbank, axes = [[1], [0]])
    spectrogram = tf.math.log(spectrogram)
    P = spectrogram.shape[0]
    if P<M:
        for k in range(M-P):
            spect_last = spectrogram[P-1]
            spect_last = tf.expand_dims(spect_last, 0)
            spectrogram = tf.concat([spectrogram, spect_last], 0)
    elif P>M:
        start = np.random.randint(0, P - M)
        spectrogram = spectrogram[start:start+M]

    return spectrogram
```
Модель я строю пока так:
```
def create_model_1(S=1024,M=15):
    inputs = layers.Input(shape = (), name = "inputs")
    x = layers.Lambda(get_spectrogram, name = 'get_spectrogram')((inputs,S,M))
    x = layers.Flatten()(x)
    x = layers.Dense(512, activation = 'relu',
                     name = "relu_1")(x)
    x = layers.Dense(512, activation = 'relu',
                     name = "relu_2")(x)
    x = layers.Dense(512, activation = 'relu',
                     name = "relu_3")(x)
    outputs = layers.Dense(12,activation = 'softmax', name = "dense_end")(x)
    model = tf.keras.Model(inputs = inputs, outputs = outputs)
    model.compile(optimizer='adam',
                  loss = 'sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model
```
Но сейчас возникает проблема, что, видимо, в функцию получения спектрограммы попадает сигнал размера как None, из-за чего работа с длиной сигнала невозможна.

**Comment by igsha** [comment]
* `X_train` - это не параметр для перебора
* Параметры `S` и `M` в слой `Lambda` нужно передавать через замыкание: `lambda x: get_spectogram(x, S, M)`
* `start = np.random.randint(0, P - M)` нужно использовать для этого `tf`. Посмотрите, как Вы делали слой Dropout для лабораторной работы №4 (https://github.com/cvlabmiet/machine-learning/blob/main/lab4.ipynb) (если она сделана правильно, конечно).

**Comment by 13Fire13nyu** [comment]
> * `X_train` - это не параметр для перебора
> * Параметры `S` и `M` в слой `Lambda` нужно передавать через замыкание: `lambda x: get_spectogram(x, S, M)`
> * `start = np.random.randint(0, P - M)` нужно использовать для этого `tf`. Посмотрите, как Вы делали слой Dropout для лабораторной работы №4 (https://github.com/cvlabmiet/machine-learning/blob/main/lab4.ipynb) (если она сделана правильно, конечно).

Так сейчас я уже не использую X_train для перебора. У меня проблема в использовании длины сигнала, потому что в процессе обучения она полагается равной None.

**Comment by igsha** [comment]
Проблема в строчке `P = spectrogram.shape[0]`? При некоторых запусках размерность не вся известна. Поэтому решения могут быть одно из:
* Используйте `tf.shape`, а не `x.shape[0]`
* Попробуйте использовать параметр `output_shape` у слоя `Lambda` (наиболее подходящий способо)
* Можете явно проверять на `None` и возвращать тензор с нужным размером (не знаю как)

**Comment by 13Fire13nyu** [comment]
Я все еще пытаюсь нормально исправить код. Сейчас моя функция получения гистограммы выглядит так:
```
def get_spectrogram(params):
    waveform = params[0]
    S = params[1]
    M = params[2]
    K = 2048
    waveform = tf.cast(waveform, tf.float32)
    spectrogram = tf.signal.stft(waveform, frame_length=K, frame_step=S, pad_end=True)
    pow_frames = (1.0 / K) * ((tf.abs(spectrogram)) ** 2)
    pow_frames = tf.where(pow_frames == 0, tf.keras.backend.epsilon(), pow_frames)  # Численная стабильность 
    # tf.keras.backend.epsilon() - машинный ноль)
    spectrogram = tf.tensordot(pow_frames, fbank, axes = [[1], [0]])
    spectrogram = tf.math.log(spectrogram)
    sh = tf.shape(spectrogram)
    P = sh[1]
    @tf.function
    def f(P,M,spectrogram):
        if P<M:
            spect_last = spectrogram[P-1]
            spect_last = tf.expand_dims(spect_last, 0)
            spectrogram = tf.concat([spectrogram, spect_last], 0)
        elif P>M:
            #start = np.random.randint(0, P - M)
            start = tf.random.uniform(shape=[], minval=0, maxval=P-M, dtype=tf.int32)
            spectrogram = spectrogram[start:start+M]
        return spectrogram

    return f(P,M,spectrogram)
```
Сама модель у меня такая:
```
def create_model_1(S=1024,M=15):
    inputs = layers.Input(shape = (None,), name = "inputs")
    x = layers.Lambda(lambda x: get_spectrogram((x, S, M)), output_shape = (M,40), name = 'get_spectrogram')(inputs)
    x = layers.Flatten()(x)
    x = layers.Dense(512, activation = 'relu',
                     name = "relu_1")(x)
    x = layers.Dense(512, activation = 'relu',
                     name = "relu_2")(x)
    x = layers.Dense(512, activation = 'relu',
                     name = "relu_3")(x)
    outputs = layers.Dense(12,activation = 'softmax', name = "dense_end")(x)
    model = tf.keras.Model(inputs = inputs, outputs = outputs)
    model.compile(optimizer='adam',
                  loss = 'sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model
```
Но теперь я даже не понимаю, откуда возникает ошибка:
![image](https://user-images.githubusercontent.com/47567199/169870161-f3e6c729-de30-48d1-a7d8-f4f7630fcda8.png)

**Comment by 13Fire13nyu** [comment]
Попробовала конвертировать данные в тензор (пришлось дополнять их до одинаковой длины), но даже при обычном обучении все равно ошибки вылазят.
Нынешний вид функции для спектрограмм:
```
def get_spectrogram(params):
    waveform = params[0]
    S = params[1]
    M = params[2]
    K = 2048
    waveform = tf.cast(waveform, tf.float32)
    spectrogram = tf.signal.stft(waveform, frame_length=K, frame_step=S, pad_end=True)
    pow_frames = (1.0 / K) * ((tf.abs(spectrogram)) ** 2)
    pow_frames = tf.where(pow_frames == 0, tf.keras.backend.epsilon(), pow_frames)  # Численная стабильность 
    # tf.keras.backend.epsilon() - машинный ноль)
    print(pow_frames.shape)
    spectrogram = tf.tensordot(pow_frames, fbank, axes = [[1], [0]])
    spectrogram = tf.math.log(spectrogram)
    sh = tf.shape(spectrogram)
    P = sh[1]
    @tf.function
    def f(P,M):
        if P<M:
            spect_last = spectrogram[P-1]
            spect_last = tf.expand_dims(spect_last, 0)
            spect = tf.concat([spectrogram, spect_last], 0)
        elif P>M:
            #start = np.random.randint(0, P - M)
            start = tf.random.uniform(shape=[], minval=0, maxval=P-M, dtype=tf.int32)
            spect = spectrogram[start:start+M]
        else:
            spect = spectrogram
        return spect
    

    return f(P,M)
```
Обучение:
```
model = create_model_1()
history = model.fit(X_train,y_train,epochs=100)
```
Ошибка: 
```
(None, None, 1025)
Epoch 1/100
(None, 140, 1025)
(None, 140, 1025)
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_3044/3731758213.py in <module>
      1 model = create_model_1()
----> 2 history = model.fit(X_train,y_train,epochs=100)

D:\anaconda3\lib\site-packages\keras\utils\traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

D:\anaconda3\lib\site-packages\tensorflow\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     52   try:
     53     ctx.ensure_initialized()
---> 54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:

InvalidArgumentError: Graph execution error:

Detected at node 'model_3677/get_spectrogram/Tensordot/MatMul' defined at (most recent call last):
    File "D:\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "D:\anaconda3\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "D:\anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "D:\anaconda3\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
      app.start()
    File "D:\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 677, in start
      self.io_loop.start()
    File "D:\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
      self.asyncio_loop.run_forever()
    File "D:\anaconda3\lib\asyncio\base_events.py", line 596, in run_forever
      self._run_once()
    File "D:\anaconda3\lib\asyncio\base_events.py", line 1890, in _run_once
      handle._run()
    File "D:\anaconda3\lib\asyncio\events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "D:\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 457, in dispatch_queue
      await self.process_one()
    File "D:\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 446, in process_one
      await dispatch(*args)
    File "D:\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 353, in dispatch_shell
      await result
    File "D:\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 648, in execute_request
      reply_content = await reply_content
    File "D:\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 353, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "D:\anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "D:\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2901, in run_cell
      result = self._run_cell(
    File "D:\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2947, in _run_cell
      return runner(coro)
    File "D:\anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
      coro.send(None)
    File "D:\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3172, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "D:\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3364, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "D:\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\belas\AppData\Local\Temp/ipykernel_3044/3731758213.py", line 2, in <module>
      history = model.fit(X_train,y_train,epochs=100)
    File "D:\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "D:\anaconda3\lib\site-packages\keras\engine\training.py", line 1384, in fit
      tmp_logs = self.train_function(iterator)
    File "D:\anaconda3\lib\site-packages\keras\engine\training.py", line 1021, in train_function
      return step_function(self, iterator)
    File "D:\anaconda3\lib\site-packages\keras\engine\training.py", line 1010, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "D:\anaconda3\lib\site-packages\keras\engine\training.py", line 1000, in run_step
      outputs = model.train_step(data)
    File "D:\anaconda3\lib\site-packages\keras\engine\training.py", line 859, in train_step
      y_pred = self(x, training=True)
    File "D:\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "D:\anaconda3\lib\site-packages\keras\engine\base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "D:\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "D:\anaconda3\lib\site-packages\keras\engine\functional.py", line 451, in call
      return self._run_internal_graph(
    File "D:\anaconda3\lib\site-packages\keras\engine\functional.py", line 589, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "D:\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "D:\anaconda3\lib\site-packages\keras\engine\base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "D:\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "D:\anaconda3\lib\site-packages\keras\layers\core\lambda_layer.py", line 196, in call
      result = self.function(inputs, **kwargs)
    File "C:\Users\belas\AppData\Local\Temp/ipykernel_3044/2380365487.py", line 6, in <lambda>
      x = layers.Lambda(lambda x: get_spectrogram((x, S, M)), output_shape = (M,40), name = 'get_spectrogram')(inputs)
    File "C:\Users\belas\AppData\Local\Temp/ipykernel_3044/1544897801.py", line 12, in get_spectrogram
      spectrogram = tf.tensordot(pow_frames, fbank, axes = [[1], [0]])
Node: 'model_3677/get_spectrogram/Tensordot/MatMul'
Matrix size-incompatible: In[0]: [32800,140], In[1]: [1025,40]
	 [[{{node model_3677/get_spectrogram/Tensordot/MatMul}}]] [Op:__inference_train_function_49831146]

```

**Comment by igsha** [comment]
> Но теперь у меня возникает ошибка подгонщика

`X_train` нужно перевести во float32: `X_train = np.asarray(X_train).astype(np.float32)`. Возможно нужно и `y_train` перевести во `float32`.

**Comment by igsha** [comment]
> Ошибка:
> spectrogram = tf.tensordot(pow_frames, fbank, axes = [[1], [0]])

Неправильные размеры для умножения: [65600,140] и [1025,40]. `fbank` имеет размер `1025x40` разве?

**Comment by 13Fire13nyu** [comment]
> > Ошибка:
> > spectrogram = tf.tensordot(pow_frames, fbank, axes = [[1], [0]])
> 
> Неправильные размеры для умножения: [65600,140] и [1025,40]. `fbank` имеет размер `1025x40` разве?

Да, у банка фильтров такие размеры.

**Comment by 13Fire13nyu** [comment]
> > Но теперь у меня возникает ошибка подгонщика
> 
> `X_train` нужно перевести во float32: `X_train = np.asarray(X_train).astype(np.float32)`. Возможно нужно и `y_train` перевести во `float32`.

Там в X_train итак изначально записаны данные float32:
![image](https://user-images.githubusercontent.com/47567199/169969594-c9d5fbdb-952d-4323-a90a-8d6f7f1619f5.png)

**Comment by 13Fire13nyu** [comment]
Я пыталась зафиксировать размер входных данных с учетом того, что принимала X_train как тензор из сигналов одного размера, написала класс слоя get_spectrogram для теста, и везде эта ошибка с размерами.

**Comment by igsha** [comment]
> Там в X_train итак изначально записаны данные float32:

Это объет `list` из `tf.Tensor` тензоров, а не массив `numpy`.

**Comment by 13Fire13nyu** [comment]
Насколько я поняла, моя сеть не очень жалует массивы numpy

**Comment by 13Fire13nyu** [comment]
Вид ошибки, если массив из массивов: ValueError: `Failed to convert a NumPy array to a Tensor (Unsupported object type numpy.ndarray).`
Вид ошибки, если массив из тензоров: `ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type tensorflow.python.framework.ops.EagerTensor)`

**Comment by 13Fire13nyu** [comment]
Попробовала привести сигналы к одному размеру, и теперь снова выдает ошибку несоответствия размеров.

**Comment by igsha** [comment]
Да не нужно их к одному размеру приводить.
Проблема осталась прежняя: неправильно умножение тензоров. На вход подаётся тензор `pow_frames`, который должен иметь размерность `[N, 15, 1025]`. Скорее всего проблема в том, что `waveform` - это матрица из звуковых файлов, а не 1-D массив.

Давайте тогда предобработку вынесем отдельно. Реализуем вне слоя. Тогда параметры нужно будет руками перебирать в цикле.

**Comment by 13Fire13nyu** [comment]
Ок, тогда буду перебирать циклом.

**Comment by igsha** [comment]
Вот эта задача становится самой актуальной, так как от неё зависит демонстрационный пример. Нам нужна функция, которая принимает на вход имена файлов и возвращает спектрограммы по схеме, которую я описывал.

**Comment by 13Fire13nyu** [comment]
Добавила код в гитхаб: [код](https://github.com/13Fire13nyu/MasterDegree/blob/master/Change_params.ipynb). Получилась точность, почти равная точности первого метода, при шаге 1024 и 10 спектрограммах на входе. Но переобучение все еще есть, а еще меня смущает матрица ошибок, точнее количества в ней:
![image](https://user-images.githubusercontent.com/47567199/171059398-28bfaf9b-a40a-4fa4-ab75-a0a97ae840f1.png)
Плюс тест на распознавание ноты ми дает такой вот результат:
![image](https://user-images.githubusercontent.com/47567199/171059451-3729f610-0a81-4dd8-99df-bd061d6a7bff.png)

**Comment by igsha** [comment]
> Но переобучение все еще есть,

Я уже не наблюдаю переобучения. График же `val_loss` идёт книзу. Медленно и неуверенно, но идёт.

> Плюс тест на распознавание ноты ми дает такой вот результат

Это нормальный результат. Просто сбалансировалось предсказание. В итоге-то оно всё= выдаст ноту ми.

Поправить: при обучении `myhistory = mymodel.fit(train_ds, validation_data=val_ds, epochs=EPOCHS)` укажите `verbose=0`, чтобы в выводе не было посторонних логов. Так будет проще читать.

**Comment by 13Fire13nyu** [comment]
> > Но переобучение все еще есть,
> 
> Я уже не наблюдаю переобучения. График же `val_loss` идёт книзу. Медленно и неуверенно, но идёт.
> 
> > Плюс тест на распознавание ноты ми дает такой вот результат
> 
> Это нормальный результат. Просто сбалансировалось предсказание. В итоге-то оно всё= выдаст ноту ми.
> 
> Поправить: при обучении `myhistory = mymodel.fit(train_ds, validation_data=val_ds, epochs=EPOCHS)` укажите `verbose=0`, чтобы в выводе не было посторонних логов. Так будет проще читать.

По поводу логов - они пока были сделаны для меня, чтобы я могла отслеживать процесс. Что насчет матрицы ошибок? До этого там значения были в пределах 300, а сейчас они выше 1000.
