### ISSUE TITLE
Модель fSTFT: Поиск оптимальных триангулярных фильтров

### ISSUE THREAD

**Issue by igsha** [13Fire13nyu/MasterDegree#15]
# Мотивация

Пики фильтров должны лежать как можно ближе к основным музыкальным частотам: `440 * (2**(1/12))**n`.

# Реализация

После генерации фильтров, проверить, куда попадают частоты фильтров. Построить идеальные фильтры:
* взять частоты от 55 до 7040 (7 октав)
* создать 84 фильтра, которые указывают на частоты `440 * (2**(1/12))**n`
* сохранить новые фильтры в новом файле (старый вариант тоже оставляем)
* **подобрать количество спектрограмм в пачке**

# Моделирование

* собрать модель с новыми фильтрами и запустить обучение
* получить результаты

**Comment by 13Fire13nyu** [comment]
Я так понимаю, что мне надо рассматривать `440 * (2**(1/12))**n` при n от -36 до 48. Но тогда получается 85 значений, а не 84.

**Comment by igsha** [comment]
Пусть будет 85. У нас будут своё распределение, зачем нам следовать примерам. У нас теперь другая процедура получения фильтров. Для левой границы используйте частоту $55 \cdot \left(\sqrt[1/12]{2}\right)^{-1}$, для правой границы - $7040 \cdot \sqrt[1/12]{2}$ (просто предполагаемые соседние ноты).
Помните, что нам нужно потом сравниваться, поэтому старый вариант тоже должен остаться.

**Comment by 13Fire13nyu** [comment]
> Пусть будет 85. У нас будут своё распределение, зачем нам следовать примерам. У нас теперь другая процедура получения фильтров. Для левой границы используйте частоту 55⋅(21/12)−1, для правой границы - 7040⋅21/12 (просто предполагаемые соседние ноты). Помните, что нам нужно потом сравниваться, поэтому старый вариант тоже должен остаться.

Там после задания ряда делается округление частот до ближайших бинов БПФ с помощью операции `f(i) = floor((nfft+1)*h(i)/samplerate)`. Но после применения этой операции некоторые мои бины совпадают. Не думаю, что это нормально.

**Comment by igsha** [comment]
Это печально. Нужно увеличивать окно.

# Теория

Дискретное преобразование Фурье сталкивается с принципом неопределённости время-частотного разрешения, которое определяется уравнением $\Delta\nu \cdot \Delta t = \frac{1}{N}$.
У нас $\Delta t = \frac{1}{44100}$ (расстояние между отсчётами во времени). Самое маленькое расстояние между частотами наблюдается в нижних частотах $\nu_0 - \nu_1 = 55\cdot\sqrt[1/12]{2} - 55 = 55 \cdot (\sqrt[1/12]{2} - 1)$.  Общая формула расстояния между соседними нотами $\Delta\nu = 55 \cdot {\sqrt[1/12]{2}}^n (\sqrt[1/12]{2} - 1)$. Величина $\Delta\nu$ неравномерная, её минимум равняется примерно 3.4. Предлагаю остановиться на $\Delta\nu = 4$, откуда полчим $N = \frac{44100}{4} = 11025$. У нас всё= будут кое-какие частоты пересекаться. Это нормально. Как странно, что раньше с такой проблемой не столкнулись.

# Практика

Увеличить окно с 2048 до 11025. Логарифмировать спектр не нужно. Необходимо посмотреть, какое окно брал Корзениовски.

**Comment by 13Fire13nyu** [comment]
> Это печально. Нужно увеличивать окно.
> 
> # Теория
> Дискретное преобразование Фурье сталкивается с принципом неопределённости время-частотного разрешения, которое определяется уравнением Δν⋅Δt=1N. У нас Δt=144100 (расстояние между отсчётами во времени). Самое маленькое расстояние между частотами наблюдается в нижних частотах ν0−ν1=55⋅21/12−55=55⋅(21/12−1). Общая формула расстояния между соседними нотами Δν=55⋅21/12n(21/12−1). Величина Δν неравномерная, её минимум равняется примерно 3.4. Предлагаю остановиться на Δν=4, откуда полчим N=441004=11025. У нас всё= будут кое-какие частоты пересекаться. Это нормально. Как странно, что раньше с такой проблемой не столкнулись.
> 
> # Практика
> Увеличить окно с 2048 до 11025. Логарифмировать спектр не нужно. Необходимо посмотреть, какое окно брал Корзениовски.

Раньше значения бинов были такие: 
```
[1.000e+00 3.000e+00 7.000e+00 1.000e+01 1.400e+01 1.800e+01 2.300e+01
 2.700e+01 3.300e+01 3.800e+01 4.500e+01 5.200e+01 5.900e+01 6.700e+01
 7.600e+01 8.500e+01 9.600e+01 1.070e+02 1.190e+02 1.330e+02 1.470e+02
 1.630e+02 1.810e+02 1.990e+02 2.200e+02 2.420e+02 2.660e+02 2.920e+02
 3.210e+02 3.520e+02 3.860e+02 4.230e+02 4.630e+02 5.060e+02 5.530e+02
 6.050e+02 6.610e+02 7.220e+02 7.880e+02 8.600e+02 9.390e+02 1.024e+03]
```
По поводу окна Корзениовски, в диссертации у него написано так: "Мы используем размер кадра 8 192 с размером перехода 4 410 при частоте дискретизации 44 100 Гц."

**Comment by igsha** [comment]
Я не очень понимаю, что такое значения бинов. Это частота (коордлината) пика триагулярных фильтров? Тогда получается, что на низких частотах был шаг в $3 - 1 = 2 \Delta\nu$. Для окна в 2048 отсчётов это соответствовует $44100/2048 = 21.53 Гц$ - это слишком большой шаг частоты для нижких частот. Нам нужно раза в 4 меньше.

У Корзениовски размер кадра почти идеальный. Нам нужно взять 11025 или даже 12600 (шаг частоты 3.5 Гц).

**Comment by 13Fire13nyu** [comment]
Мне кажется, что я делаю что-то не то: 
![image](https://user-images.githubusercontent.com/47567199/171492292-98f2f6bb-7615-47b5-93fa-83916f599973.png)

На всякий случай кидаю [код](https://github.com/13Fire13nyu/MasterDegree/blob/master/filterbanks.ipynb)

**Comment by igsha** [comment]
Всё нормально.
```
[  13.   14.   15.   16.   17.   18.   19.   20.   21.   23.   24.   25.
   27.   29.   30.   32.   34.   36.   38.   41.   43.   46.   49.   51.
   55.   58.   61.   65.   69.   73.   77.   82.   87.   92.   98.  103.
  110.  116.  123.  130.  138.  146.  155.  164.  174.  185.  196.  207.
  220.  233.  246.  261.  277.  293.  311.  329.  349.  370.  392.  415.
  440.  466.  493.  523.  554.  587.  622.  659.  698.  740.  784.  830.
  880.  932.  987. 1046. 1108. 1174. 1244. 1318. 1397. 1480. 1568. 1661.
 1760.]
```
Это получились отсчёты, которые соответсвуют нашим частотам. Мы используем только часть спектра до 7040 Гц, что соответсвует отсчёту 1760. Всего отсчётов в спектре будет 11025//2.
Сохраните полученный фильтр и проведите эксперименты по обучению.

**Comment by 13Fire13nyu** [comment]
У меня проблема по согласованию размеров данных. Мощность спектра имеет 2**`(np.ceil(np.log2(11025))-1)+1=11025/2+1=8193` отсчета, в то время как у фильтров `np.floor(NFFT/2)+1=11025/2+1=5513` отсчетов. Из-за этого я не могу перемножить мощность и фильтры.

**Comment by 13Fire13nyu** [comment]
Пока что решила попробовать сделать для размера окна 8192 и 83 фильтров. Для 100 эпох картина такая:
![image](https://user-images.githubusercontent.com/47567199/171791332-d383c9a9-eee2-48ff-8d97-bdfc0a9d2929.png)
![image](https://user-images.githubusercontent.com/47567199/171791363-85f40654-b56c-4a81-b006-986485ac2a4d.png)
Для изменения количества эпох код я запустила.

**Comment by igsha** [comment]
Почему мощность спектра получается 8193 отсчёта? https://www.tensorflow.org/api_docs/python/tf/signal/stft тут написано, что она составляется `11025 // 2 + 1 = 5513`. Откуда формула $2^{\lceil \log_2{(11025)} - 1\rceil} + 1$?

**Comment by 13Fire13nyu** [comment]
Ну судя по тому, что всегда получалось:
![image](https://user-images.githubusercontent.com/47567199/171791897-4d33ebb1-4703-45c2-8697-249402f8f1d1.png)
И значение 8193 даже сама функция выдает.

**Comment by igsha** [comment]
Это верно для БПФ, которое оптимизировано для $2^n$ отсчётов. Современные методы позволяют любое кратное ускорять.
А какая функция выдаёт? `tf.signal.stft`?

**Comment by 13Fire13nyu** [comment]
> Это верно для БПФ, которое оптимизировано для 2n отсчётов. Современные методы позволяют любое кратное ускорять. А какая функция выдаёт? `tf.signal.stft`?

Да

**Comment by 13Fire13nyu** [comment]
Для 83 фильтров и размера окна 11025 у меня получилось, что лучший результат был достигнут на 100 эпохах и для шага 2048 и 45 спектрограмм. Точность равна 94.78 %. Но переобучение тоже есть:
![image](https://user-images.githubusercontent.com/47567199/172041089-9b34cc81-adcf-4b15-a07d-466cfab6d6b0.png)

**Comment by 13Fire13nyu** [comment]
Скорее всего, получившиеся результаты дают слишком большой промежуток времени, потому что демонстрация оставляет желать лучшего:
![image](https://user-images.githubusercontent.com/47567199/172046968-fae10900-ad33-46bc-891b-022a82bdce63.png)

**Comment by igsha** [comment]
Нам нужно посмотреть на спектрограммы. Насколько они отличаются от первой модели?

**Comment by 13Fire13nyu** [comment]
Это для модели 1:
![image](https://user-images.githubusercontent.com/47567199/172052117-4b6a0ae7-0942-42ab-88e1-45748dcd1c1a.png)
Это для модели 4:
![image](https://user-images.githubusercontent.com/47567199/172052244-8c93a015-af31-4504-879e-4ff101f087a3.png)

**Comment by igsha** [comment]
Тут что-то не так: спектрограммы почти нулевые. У нас не хватает длины данных при обучении? В файлах есть хотя бы 11025 отсчётов?

**Comment by 13Fire13nyu** [comment]
> Тут что-то не так: спектрограммы почти нулевые. У нас не хватает длины данных при обучении? В файлах есть хотя бы 11025 отсчётов?

Видимо, не во всех:
![image](https://user-images.githubusercontent.com/47567199/172053030-72f3c9db-b158-4b17-b3c5-cdce80fdbcef.png)

**Comment by igsha** [comment]
Зависимость от #20

**Comment by 13Fire13nyu** [comment]
Результаты:
Действия аналогичны тем, что были произведены для моделей STFT и MFCC. Задержка ранней остановки - 10 эпох. Количество фильтров - 83. Результаты селудющие:
![image](https://user-images.githubusercontent.com/47567199/172798403-c5a8ad38-2859-435a-ac2f-a590661b585e.png)
Точность - 96.37% (Самый высокий результат среди всех четырех моделей). Лучшие параметры - шаг 1024 и 20 спектрограмм. Время выполнения - 1 минута 3 секунды.
![image](https://user-images.githubusercontent.com/47567199/172798783-050b28ca-334e-4339-9c2c-be0a3478d8ab.png)
![image](https://user-images.githubusercontent.com/47567199/172798821-2c6cb495-e1c9-4183-a101-63fb927712f1.png)
![image](https://user-images.githubusercontent.com/47567199/172798841-200545c0-6b39-4507-8ca1-841104b2f9ad.png)
Вид спектрограмм:
![image](https://user-images.githubusercontent.com/47567199/172798909-738ad405-4b79-40fa-bede-ae8f348c21b7.png)
Для 50 эпох: точность повысилась (96.52%), но есть переобучение
![image](https://user-images.githubusercontent.com/47567199/172799078-140a6e10-a209-450e-9748-ed8048d53277.png)

**Comment by igsha** [comment]
`Время выполнения - 1 минута 3 секунды.` - это время обучения?

**Comment by 13Fire13nyu** [comment]
> `Время выполнения - 1 минута 3 секунды.` - это время обучения?

да

**Comment by igsha** [comment]
А почему справа на спектрограммах нет полос? Я такое наблюдаю во всех моделях. Каких-то данных не хватает?

**Comment by 13Fire13nyu** [comment]
Ну, видимо, не хватает данных, чтобы были нужное количество спектрограмм и заданный шаг. Может быть, сигнал заканчивался значением, близким к нулю, поэтому распространился именно он.

**Comment by igsha** [comment]
То есть, дублирование правого края спектрограмм присутствует?

**Comment by 13Fire13nyu** [comment]
Да

**Comment by igsha** [comment]
То есть это проблема коротких данных. Попробуйте размножать не последнюю спектрограмму, а среднее значение всех предыдущих. По картинкам будет видно, правильно ли сделано расширение или нет. Посмотрим, как это отразится на результатах.

**Comment by 13Fire13nyu** [comment]
Это во всех моделях так делать?

**Comment by 13Fire13nyu** [comment]
Как можно найти среднее тензоров?

**Comment by 13Fire13nyu** [comment]
Для STFT у меня такие вышли: 
![image](https://user-images.githubusercontent.com/47567199/172807383-1f9da032-f42c-4807-bd10-d35bfba954c2.png)

**Comment by 13Fire13nyu** [comment]
Могу сказать сразу, что обучение стало дольше.

**Comment by 13Fire13nyu** [comment]
Я смотрю результаты fSTFT, они стали немного, но похуже

**Comment by 13Fire13nyu** [comment]
Вот спектрограммы:
![image](https://user-images.githubusercontent.com/47567199/172818321-967aefb8-2ece-49ad-a95d-c1bd125086dc.png)

**Comment by 13Fire13nyu** [comment]
Может, при получении среднего получается какой-то грязный звук, который распознается хуже?

**Comment by igsha** [comment]
Вот эти пустоты как-то портят статистику. Откуда они появляются? Попробуйте использовать параметр `pad_end=False` при `stft`, чтобы не попадало неполных данных на конец. Мне кажется, что именно разрыва портят результат.

**Comment by 13Fire13nyu** [comment]
![image](https://user-images.githubusercontent.com/47567199/172820986-15b15528-a744-4efc-87e4-a2251f3a3eba.png)

**Comment by igsha** [comment]
Так хорошо. Теперь давайте пробовать расширять либо последним, либо средним. Нам нужны оба результата. Из них выберем лучший.

**Comment by 13Fire13nyu** [comment]
Пока обучаю на среднем. Мне эти процедуры и для остальных моделей проделывать?

**Comment by 13Fire13nyu** [comment]
Результат не стал лучше изначального - 96.19%.

**Comment by 13Fire13nyu** [comment]
![image](https://user-images.githubusercontent.com/47567199/172828904-b658dbbf-b190-4f84-b737-a8197648a745.png)

**Comment by igsha** [comment]
> Пока обучаю на среднем. Мне эти процедуры и для остальных моделей проделывать?

Пока нам нужно понять, что лучше: просто последний размножать или среднее.

**Comment by 13Fire13nyu** [comment]
Время обучения - 1 минута 2 секунды.
![image](https://user-images.githubusercontent.com/47567199/172829971-2ccffab1-5211-4f0a-a91e-63f1498fb29b.png)
![image](https://user-images.githubusercontent.com/47567199/172829992-02fde5a6-e9cb-4ecb-8acb-cb93f1b476c8.png)
![image](https://user-images.githubusercontent.com/47567199/172830012-def46dcd-585f-48fb-b57c-024256ffc04b.png)
![image](https://user-images.githubusercontent.com/47567199/172830063-d360e7f4-37a0-457c-aa7f-b5c6999a1b2e.png)
![image](https://user-images.githubusercontent.com/47567199/172830092-2e4ea1e3-c21c-4790-a3ed-5a6ef1313768.png)
![image](https://user-images.githubusercontent.com/47567199/172830120-ea2cba6c-104d-47d4-a6cc-b2fe3ff0142b.png)
Точность 96.26%

**Comment by 13Fire13nyu** [comment]
Для дополнения последним: Точность 96.15%, время обучения: 52 секунды
![image](https://user-images.githubusercontent.com/47567199/172838573-0b318da4-2141-4d36-82be-1414eda60ae0.png)
![image](https://user-images.githubusercontent.com/47567199/172838622-4b7827c1-f2c8-42af-aa8f-ef4f5044137d.png)
![image](https://user-images.githubusercontent.com/47567199/172838679-aee892a8-e537-46cf-a6d3-56d1f2e36a53.png)
![image](https://user-images.githubusercontent.com/47567199/172838694-316058ef-5bd2-45e3-9dbe-fafb2a3e49e3.png)
![image](https://user-images.githubusercontent.com/47567199/172838734-27a5c12f-49c1-471b-83a6-64e6e1f25f70.png)
![image](https://user-images.githubusercontent.com/47567199/172838759-85877280-d783-4ae2-812b-9da0b07361be.png)
![image](https://user-images.githubusercontent.com/47567199/172838780-4d8cd7f0-f891-4c19-91f8-a75bd475f8b1.png)
Точность - 95.30%

**Comment by 13Fire13nyu** [comment]
Сейчас лучше на 0.04% модель с усреднением.

**Comment by igsha** [comment]
Да разница особо небольшая. Размножение последнего более привлекательно, так как меньше нужно вычислений.
