### ISSUE TITLE
Модель mDCT

### ISSUE THREAD

**Issue by igsha** [13Fire13nyu/MasterDegree#16]
# Мотивация

Использование оконного DCT вместо STFT.

# Реализация

* создать ещё одну функцию `get_spectrogram`
* заменить `tf.signal.stft` на https://www.tensorflow.org/api_docs/python/tf/signal/mdct
* удалить параметр шага окна, так как mdct всегда использует половину окна в качестве шага
* **подобрать количество спектрограмм в пачке**

# Моделирование

* обучить модель с новым слоем получения спектрограммы
* получить результаты
* сравнить результаты со старыми подходами

**Comment by 13Fire13nyu** [comment]
Попробовала сделать при окне 2048, количестве спектрограмм 15 и 100 эпохах без фильтров (размеры не совпадают, потому что у фильтров одна из размерностей 1025, а у ДКП - 1024). Спектрограммы получились такие:
![image](https://user-images.githubusercontent.com/47567199/172049121-e4ab2939-f8ca-4d8e-bdd7-b8638e196c2c.png)
Точность равна 89.02%. Переобучение довольно сильное:
![image](https://user-images.githubusercontent.com/47567199/172049149-990dd0d8-31d5-4dab-9bd8-e02fb8738c0f.png)

**Comment by 13Fire13nyu** [comment]
Для демонстрации получились следующие результаты:
![image](https://user-images.githubusercontent.com/47567199/172051333-16190c6c-7de6-43d5-89a5-c2238c67c8a3.png)
![image](https://user-images.githubusercontent.com/47567199/172051346-a2f1b43e-334e-47b5-93e9-7d08f27e75cf.png)

**Comment by igsha** [comment]
Зачем нам тут демонстрации? Мы хотим сравнить STFT и mDCT. Тут нет никаких фильтров.

**Comment by 13Fire13nyu** [comment]
> Зачем нам тут демонстрации? Мы хотим сравнить STFT и mDCT. Тут нет никаких фильтров.

Ну вот я и не использовала фильтры.

**Comment by igsha** [comment]
Первая модель лучше этой?

**Comment by 13Fire13nyu** [comment]
> Первая модель лучше этой?

При текущих параметрах в ДКП - да. Но можно подбирать количество спектрограмм.

**Comment by igsha** [comment]
В текущих реалиях ДКП проигрывает. Давайте подберём параметры. Вставим это исследование в диссертацию с намёком, что ДКП не подходит для гармонического анализа.

**Comment by 13Fire13nyu** [comment]
> В текущих реалиях ДКП проигрывает. Давайте подберём параметры. Вставим это исследование в диссертацию с намёком, что ДКП не подходит для гармонического анализа.

Хорошо, код подготовлен, но пока не запущен из-за предыдущей задачи. Хотя, как я понимаю, придется там исправлять из-за большого окна. Для ДКП я подбираю количество спектрограмм и количество эпох.

**Comment by igsha** [comment]
Зависимость от #20

**Comment by 13Fire13nyu** [comment]
Мною были рассмотрены 6 вариантов количества спектрограмм в одной пачке: 1, 3, 5, 10, 15 и 20. Для ускорения обучения я применила механизм ранней остановке на основе потерь на проверочной выборке с задержкой на 10 эпох. Максимальное количество эпох было установлено равным 300. В итоге можно наблюдать, что для всех вариантов количества спектрограмм обучение совершалось на 10 эпохах. Зависимость точности от количества спектрограмм выглядит так:
![image](https://user-images.githubusercontent.com/47567199/172588560-99a075a5-b669-45ad-91f2-cc1f1fe2dd45.png)
Максимальная точность была достигнута при 3 спектрограммах и составила 88.67%. Графики штрафа и точности получились следующие:
![image](https://user-images.githubusercontent.com/47567199/172588860-fb30d6c3-631a-44b3-9d23-6f5d65665537.png)
Далее - матрица ошибок и тестовое распознавание ноты E:
![image](https://user-images.githubusercontent.com/47567199/172588937-41bd3e9e-1bf0-4270-95de-f804cf63b7a6.png)
![image](https://user-images.githubusercontent.com/47567199/172588954-ae2ed869-454a-4e72-9d2a-ca0a61892346.png)
Спектрограммы при подходе mDCT показывают, почему точность довольно низкая - они практически не отображают никакой информации.
![image](https://user-images.githubusercontent.com/47567199/172589134-6bc60e54-38f0-47a7-84ba-8bfbeb06c57f.png)
При увеличении количества эпох до 50 получаются следующие графики штрафа и точности:
![image](https://user-images.githubusercontent.com/47567199/172589255-994d391b-e1ab-4d53-9226-96ec4ba9947f.png)
Штраф растет, а точность обучения стала горизонтальной, что является признаком предела архитектуры.

**Comment by igsha** [comment]
Считаем исследование по этой моделе завершённым.

**Comment by 13Fire13nyu** [comment]
Для pad_and = False: Точность - 88.55%, время обучения - 1 минута 20 секунд
![image](https://user-images.githubusercontent.com/47567199/172887980-62d2e868-2734-4e81-b4c6-b254d92be872.png)
![image](https://user-images.githubusercontent.com/47567199/172888228-fa03cab7-1898-4a90-b58c-263d7c54c462.png)
![image](https://user-images.githubusercontent.com/47567199/172888244-2862dac3-b4c3-434f-98d3-b5cfcebe5312.png)
![image](https://user-images.githubusercontent.com/47567199/172888268-5cf1c89f-a376-4510-b074-61afbfb3faec.png)
![image](https://user-images.githubusercontent.com/47567199/172888281-fd5f33a2-5b85-42fa-b0c6-2eaf7d97a7b4.png)
![image](https://user-images.githubusercontent.com/47567199/172888306-2b57ca10-62e0-4ddb-a72c-94305818c01c.png)
50 эпох: точность - 87.78%
![image](https://user-images.githubusercontent.com/47567199/172888393-baf40996-214d-42d0-b6e5-131727f9df8f.png)
