### ISSUE TITLE
Написание текста диссертации

### ISSUE THREAD

**Issue by igsha** [13Fire13nyu/MasterDegree#17]
# Мотивация

Закончить обучение в магистратуре.

# Реализация

1. Получение плана диссертации с обозначениями разделов
2. Описание обзора существующих методов
3. Описание исследований
4. Описание результатов исследований
5. Заключения

**Comment by 13Fire13nyu** [comment]
План:

- Аннотация
- Оглавление
- Введение
- Глава 1. Обзор существующих методов

1.1. LeNet5
1.2. AlexNet
1.3. VGG16
1.4. Inception и GoogLeNet
1.5. ResNet
1.6. ENet
1.7. MobileNet
1.8. YOLO

- Глава 2. Исследование получения основной гармоники

2.1. Подготовка базы данных для распознавания нот
2.2. Генерация спектрограмм
2.3. Формирование архитектуры нейронной сети
2.4. Входные данные и параметры спектрограмм
2.5. Изменение шага окна и количества кадров, подаваемых на вход нейросети
2.6. Борьба с переобучением
2.7. Поиск оптимальных треугольных фильтров
2.8. Применение ДКП

- Глава 3. Результаты исследования
- Заключение
- Список литературы

**Comment by igsha** [comment]
Глава 1: Не нужно рассматривать столько сетей. Рассмотрите только одну, но подробно.
Глава 2:
* `Входные данные и параметры спектрограмм` - это должно идти после спектрограмм.
* `Изменение шага окна и количества кадров, подаваемых на вход нейросети` - это тоже после спектрограмм.
* Во 2-й главе хорошо просматривается 2 раздела: предобработка и нейронная сеть. Почти всё уходит подразделами в предобработку.

**Comment by 13Fire13nyu** [comment]
Пишу вторую главу, но пока не совсем понимаю, что следует писать про изменение шага окна и поиск оптимальных треугольных фильтров.

**Comment by igsha** [comment]
> Пишу вторую главу, но пока не совсем понимаю, что следует писать про изменение шага окна и поиск оптимальных треугольных фильтров.

Сначала нужно их найти, чтобы было понятно как описывать. Шаг окна Вы уже нашли и можете описать эту процедуру.

**Comment by 13Fire13nyu** [comment]
Мое текущее оглавление.
АННОТАЦИЯ	2
ВВЕДЕНИЕ	4
ГЛАВА 1. ОБЗОР СУЩЕСТВУЮЩИХ МЕТОДОВ	6
ГЛАВА 2. ИССЛЕДОВАНИЕ ПОЛУЧЕНИЯ ОСНОВНОЙ ГАРМОНИКИ	12
2.1.	Предобработка	12
2.1.1.	Подготовка базы данных для распознавания нот	12
2.1.2.	Генерация спектрограмм	14
2.1.3.	Параметры входных данных	20
2.1.4.	Применение модифицированного дискретного косинусного преобразования	23
2.1.5.	Итоговые модели предобработки	24
2.2.	Нейронная сеть	24
ГЛАВА 3. РЕЗУЛЬТАТЫ ИССЛЕДОВАНИЯ	29
ЗАКЛЮЧЕНИЕ	53
СПИСОК ЛИТЕРАТУРЫ	54
Осталось добавить демонстрационные примеры и работа будет завершена. Сейчас 55 страниц.

**Comment by 13Fire13nyu** [comment]
Версия текста диссертации без демонстрационных примеров: [файл](https://drive.google.com/file/d/1MAxTa9PRIxdrddVSVW0cqoTJh4_oTXLi/view?usp=sharing)

**Comment by igsha** [comment]
Оставил комментарии к тексту.

**Comment by 13Fire13nyu** [comment]
> Оставил комментарии к тексту.

Написала некоторые ответы к комментариям

**Comment by 13Fire13nyu** [comment]
Мне пункт 2.1.2 полностью в первую главу переносить?

**Comment by igsha** [comment]
> Мне пункт 2.1.2 полностью в первую главу переносить?

Да. Во второй главе спектрограммы уже должны быть известны, нужно только показать, какие параметры нужно у спектрограммы подобрать.

**Comment by 13Fire13nyu** [comment]
> Таблица поможет. Но проще же все параметры подбирать по моделям. Именно так сейчас и сделано.

Да, но не хочется писать одно и то же.

**Comment by 13Fire13nyu** [comment]
Куда я могу прислать текст из главы 1 про звук? Я не совсем понимаю, все ли я там учла.

**Comment by igsha** [comment]
Туда же кидайте. Только все замечания сначала поправьте, чтобы они не затерялись. Суетиться не нужно. Если что-то не успеется, то не успеется. Нам нужно добиться хотя бы, чтобы в диссертации было полное описание для повторяемости эксперимернов. В заключении также напишите, что конкретно Вы подбирали (например, 40 мел-фильтров Вы не подбирали, а взяли из литературы). То есть нужно в конце подчеркнуть собственный вклад.

**Comment by igsha** [comment]
Если что, я могу договориться, чтобы продлили тестирование на антиплагиат для Вашей работы. Но ругать всё= будут за это, конечно.

**Comment by 13Fire13nyu** [comment]
Моя основная проблема сейчас - это демонстрационные примеры, потому что там, как видно, что-то не то.

**Comment by igsha** [comment]
Ну давайте пока всё сделаем без них.

**Comment by 13Fire13nyu** [comment]
Отредактировала пока то, что смогла: https://drive.google.com/file/d/13mOeTwEPkVFKk-P8TlHdhIKqZI1r8NjS/view?usp=sharing

**Comment by igsha** [comment]
Сейчас хорошо выглядит. Страниц хватает? Очень хочется всё-таки вставить демонстрационный пример.

**Comment by 13Fire13nyu** [comment]
> Сейчас хорошо выглядит. Страниц хватает? Очень хочется всё-таки вставить демонстрационный пример.

Да, там все еще 55 страниц. Соображения по поводу демонстрационных примеров я прислала в вопрос.

**Comment by 13Fire13nyu** [comment]
Я еще делала сама проверку на антиплагиат (благо, есть источник). Там, в принципе все хорошо:
![image](https://user-images.githubusercontent.com/47567199/173601930-29bcb365-0eef-49b4-a300-659a277ac3c5.png)

**Comment by 13Fire13nyu** [comment]
Все поправила. Вроде как, готовый вариант: https://drive.google.com/file/d/14vwpESniHqR6Ny4cqGdz7XfzkxQOG5u2/view?usp=sharing

**Comment by igsha** [comment]
Какой шрифт использовался?

**Comment by 13Fire13nyu** [comment]
> Какой шрифт использовался?

Times New Romans 13

**Comment by 13Fire13nyu** [comment]
А зачем ещё одну главу выделять, если они и так маленькие?

**Comment by igsha** [comment]
> А зачем ещё одну главу выделять, если они и так маленькие?

Не главу а подраздел.

**Comment by 13Fire13nyu** [comment]
> > А зачем ещё одну главу выделять, если они и так маленькие?
> 
> Не главу а подраздел.

И всё же зачем?

**Comment by igsha** [comment]
Вставьте тогда приложение с кодом демонстрационного примера. Только почистите его от комментариев. В подразделе демонстрационного примера напишите, что код можно посмотреть в приложении.

**Comment by igsha** [comment]
> И всё же зачем?

Ну потому что это что-то отдельное. Вы же ставите точку, когда хотите отделить мысли друг от друга. Плюс больше места можно израсходовать. Нам бы до 60 страниц довести.

**Comment by 13Fire13nyu** [comment]
> > И всё же зачем?
> 
> Ну потому что это что-то отдельное. Вы же ставите точку, когда хотите отделить мысли друг от друга. Плюс больше места можно израсходовать. Нам бы до 60 страниц довести.

Просто сейчас пункт 3.5 и так маленький, А сравнение путём примера по сути стыкуется с общим сравнением. К тому же по идее количество страниц - от 50...

**Comment by 13Fire13nyu** [comment]
С приложением получается больше 60 страниц

**Comment by igsha** [comment]
Это на кафедре сказали, что от 50 страниц нужно?

**Comment by igsha** [comment]
> пункт 3.5 и так маленький

Проблема не в размере, а как ссылаться на демонстрационный пример. Если он будет прямо в огравлении, тогда будет понятно, что он есть. Сейчас он как будто спрятан.

**Comment by 13Fire13nyu** [comment]
Обновила: https://drive.google.com/file/d/14vwpESniHqR6Ny4cqGdz7XfzkxQOG5u2/view?usp=sharing

**Comment by 13Fire13nyu** [comment]
В итоге 67 страниц

**Comment by igsha** [comment]
Таак, выяснил. Это в ориоксе есть методичка, в которой написано про 50-60 страниц. Тогда не нужно вставлять приложений. Удаляйте тогда приложение и можете отсылать диссертацию на антиплагиат Назарову.

**Comment by 13Fire13nyu** [comment]
Ок

**Comment by 13Fire13nyu** [comment]
Исправила

**Comment by 13Fire13nyu** [comment]
Отправила на проверку

**Comment by igsha** [comment]
Оригинальность работы составила 90.22%
