### ISSUE TITLE
Презентация для защиты

### ISSUE THREAD

**Issue by igsha** [13Fire13nyu/MasterDegree#18]
Список замечаний для презентации после предзащиты:
* Слайд №7 - что такое частота мелодии? Может это частота дискретизации?
* Слайд №10 - формула (11) выглядит подозрительной
* Слайд №13 перегружен информацией. Требуется либо разбить его, либо сократить
* Слайд №14 - перевёрнута спектрограмма
* Слайд №16 - использовать красный цвет, а не оранжевый

**Comment by 13Fire13nyu** [comment]
Насколько сильно должна измениться моя прежняя презентация с учётом написанного в дипломе?

**Comment by igsha** [comment]
Графики переделать, демонстрационный пример теперь другой. И нужно показать все модели.

**Comment by 13Fire13nyu** [comment]
Имеет ли смысл оставлять слайды 15 и 16, если есть полная таблица для сравнения? Иначе это может надолго затянуться.

**Comment by igsha** [comment]
Сделайте сначала всё, потому ненужные слайды удалим.

**Comment by 13Fire13nyu** [comment]
https://drive.google.com/file/d/1-aBpa7c3dlKcEJJCZsGh3QBr5NdDUQtD/view?usp=sharing

**Comment by 13Fire13nyu** [comment]
Новый вариант презентации: https://drive.google.com/file/d/1bspGErfYAbjLk39gr705rSLwudY3ISah/view?usp=sharing

**Comment by igsha** [comment]
Поправьте последние изменения. На этом считаем задачу выполненной.
