### ISSUE TITLE
Список исследуемых моделей

### ISSUE THREAD

**Issue by igsha** [13Fire13nyu/MasterDegree#19]
# Мотивация

Нет чёткого понимания, что представляет из себя исследуемые модели.

# Терминология

* Окно и фрейм - это одно и то же
* STFT возвращает несколько спектрограмм. Будем называть это пачкой спектрограмм
* Нейросеть всегда принимает пачку спектрограмм. Так как нейросеть не универсальна, её нужно обучать для данного размера пачки

# Список

| Название модели | Описание модели | Параметры модели для исследования |
|:------------------------:|:--------------------------:|:-----------------------------------------------------:|
| Модель STFT | Только `abs(tf.signal.stft)**2` | Размер окна, шаг окна, количество спектрограмм в пачке
| Модель mDCT | Только `tf.signal.mdct` | Размер окна, количество спектрограмм в пачке
| Модель MFCC | abs(STFT)**2 + filters + log + DCT | Размер окна, количество спектрограмм в пачке, фильтры мел задаются обычные (по 40 бинов)
| Модель fSTFT | `abs(tf.signal.stft)**2` + filters | Размер окна, шаг окна, количество спекторамм в пачке, фильтры на 85-86 октав

Проверить, правильно ли я всё описал. Может ещё какие-то модели есть.

# Требования

На каждуй из моделей создать свой ipynb файл с сохранением модели. Запуск демонстрационного примера можно сделать единый для разных моделей в одном ipynb файле. Использовать вариант демонстарции с `imshow`.

Удалить какие-то старые и непонятные версии из репозитория. Только то, что исследуем. Остальное помнит git.

**Comment by 13Fire13nyu** [comment]
Модель STFT: разве там должен быть квадрат? Изначально этого не было оговорено.
Модель fSTFT: количество фильтров - 83.
Разве надо было исследовать размер окна тоже?

**Comment by igsha** [comment]
> Модель STFT: разве там должен быть квадрат? Изначально этого не было оговорено.

Значения действительные у спектра? Если комплексные, то нужен квадрат. Квадрат всё= не помешаяет.

> Разве надо было исследовать размер окна тоже?

Вы же сейчас именно это и делаете, когда берёте 11025 отсчётов. Вычислите среднюю длину файла в базе в отчётах. У меня есть подозрение, что мы не можем брать большие окна из-за коротких файлов. Тогда нам придётся оперировать только шагом окна.

**Comment by 13Fire13nyu** [comment]
> > Модель STFT: разве там должен быть квадрат? Изначально этого не было оговорено.
> 
> Значения действительные у спектра? Если комплексные, то нужен квадрат. Квадрат всё= не помешаяет.
> 
> > Разве надо было исследовать размер окна тоже?
> 
> Вы же сейчас именно это и делаете, когда берёте 11025 отсчётов. Вычислите среднюю длину файла в базе в отчётах. У меня есть подозрение, что мы не можем брать большие окна из-за коротких файлов. Тогда нам придётся оперировать только шагом окна.

А если среднее получится больше размера части файлов (а это вполне реально)? Некоторые файлы существенно длиннее большей части. Есть примеры, где более 60000 отсчетов и где примерно 7000.

**Comment by igsha** [comment]
Значит будем оперировать размером пачки спектрограмм. Должно дать тот же эффект. Выведите ещё минимальное значение длины данных в файлах.

**Comment by 13Fire13nyu** [comment]
Еще такой вопрос: в [задаче](https://github.com/13Fire13nyu/MasterDegree/issues/5#issue-1209912486) размером 2048 мы оперировали как близким к максимальному размеру окна. Как объясняется увеличение размера до 11025 (ну или другому в зависимости от среднего и минимального)?

**Comment by igsha** [comment]
Из-за этого https://github.com/13Fire13nyu/MasterDegree/issues/15#issuecomment-1141732559

**Comment by 13Fire13nyu** [comment]
Ок

**Comment by 13Fire13nyu** [comment]
Вопрос по поводу модели MFCC: там разве не надо квадрат модуля STFT делить на размер окна? Изначально так получалась мощность, над которой происходили дальнейшие манипуляции.

**Comment by 13Fire13nyu** [comment]
Количество данных, длина которых меньше средней - 11811. Всего данных при этом - 19590. Т.е. получается больше половины данных короче средней длины. При этом только 5 штук короче длины 2048.

**Comment by 13Fire13nyu** [comment]
Меня смущают результаты, получающиеся при добавлении квадрата в модель STFT. Точность ухудшилась (стала равна 92. 89%), а штраф ведет себя крайне странно: 
![image](https://user-images.githubusercontent.com/47567199/172299628-e3d3cf47-c1ab-47b8-86e7-2ba5c84dd945.png)

**Comment by igsha** [comment]
> Количество данных, длина которых меньше средней - 11811. Всего данных при этом - 19590. Т.е. получается больше половины данных короче средней длины. При этом только 5 штук короче длины 2048.

Значит, мы не можем брать большие окна. В итоговой мелодии, какая самая низкая нота в Гц?

**Comment by igsha** [comment]
> Меня смущают результаты, получающиеся при добавлении квадрата в модель STFT. Точность ухудшилась (стала равна 92. 89%), а штраф ведет себя крайне странно: ![image](https://user-images.githubusercontent.com/47567199/172299628-e3d3cf47-c1ab-47b8-86e7-2ba5c84dd945.png)

Видно же, что нужно останавливаться на эпохе около 20-30, потом начинается настолько жёсткое переобучение, что даже точность на тренировочной выборке ухудшается.

**Comment by igsha** [comment]
> Вопрос по поводу модели MFCC: там разве не надо квадрат модуля STFT делить на размер окна? Изначально так получалась мощность, над которой происходили дальнейшие манипуляции.

Да, нужно. Нормализовать нужно и обычную модель STFT, если в tensorflow этого не сделано.

**Comment by igsha** [comment]
В итоге у нас 4 модели. Под каждую модель создал отдельную задачу.

**Comment by 13Fire13nyu** [comment]
А что по поводу размера окна в итоге?

**Comment by 13Fire13nyu** [comment]
> 

Имеется в виду в самой функции stft от tensorflow? Как это можно проверить?

**Comment by igsha** [comment]
> Имеется в виду в самой функции stft от tensorflow? Как это можно проверить?

1. Почитать документацию
2. Запустить `tf.signal.stft` для сигнала `m = np.zeros((N,)); m[0] = 1` и посмотреть, чему равна мощность.

**Comment by 13Fire13nyu** [comment]
> > Имеется в виду в самой функции stft от tensorflow? Как это можно проверить?
> 
> 1. Почитать документацию
> 2. Запустить `tf.signal.stft` для сигнала `m = np.zeros((N,)); m[0] = 1` и посмотреть, чему равна мощность.

![image](https://user-images.githubusercontent.com/47567199/172319848-1288933e-6a38-450c-8383-0e586058c738.png)

**Comment by 13Fire13nyu** [comment]
В документации слишком как-то мало информации. Про нормировку не вижу

**Comment by 13Fire13nyu** [comment]
Так, код я запустила, и нормы оказались равны. Значит, надо все же делить на длину?

**Comment by igsha** [comment]
> Так, код я запустила, и нормы оказались равны. Значит, надо все же делить на длину?

Я не понимаю к чему вопрос. Везде, где требуется `tf.signal.stft(..., frame_length=N, ...)` пишите `tf.signal.stft(..., frame_length=N, ...) / np.sqrt(N//2 + 1)`. После возведения в квадрат спектра делить его уже ни на что не нужно. Раньше у Вас при возведении в квадрат была заложена нормировка.

Почему это всё так важно? Потому что у нас в сети нет нормализационных слоёв. Вводить их уже поздно да и смысла особо нет, если все данные будут отнормированны.
