### ISSUE TITLE
Обучение нейронной сети

### ISSUE THREAD

**Issue by igsha** [13Fire13nyu/MasterDegree#2]
Согласно подходу, описанному в https://www.researchgate.net/publication/331276600_Harmonic_Analysis_of_Musical_Audio_using_Deep_Neural_Networks.

### Описание

Архитектура сети:
![image](https://user-images.githubusercontent.com/5345170/155129643-067bf99c-37fe-43cc-ba61-8bab23584383.png)

```
Input(2670)
3xDense(512, relu)
Dense(12, sigmoid)
```

Попробовать данную архитектуру обучить на полученном датасете #1.
В качестве входных данных использовать коэффициенты mfcc.

### Результаты

Получение рабочего кода по распознаванию аккордров. Проанализировать полученные результаты, какая получилась производительность и точность.

**Comment by 13Fire13nyu** [comment]
[Код](https://github.com/13Fire13nyu/MasterDegree/blob/master/Data_fitting_v1.ipynb)
