### ISSUE TITLE
Поиск оптимального размера окна

### ISSUE THREAD

**Issue by igsha** [13Fire13nyu/MasterDegree#20]
# Мотивация

Минимальный размер окна для вмещения 84 октав - 2048 отсчётов для дискретизации 44100 (~21 Гц между отсчётами по частоте). Минимальный шаг частоты должен быть 3-3.5 Гц, что соответствует около 12600 отсчётам для дискретизации 44100.

# Реализация

В базе слишком короткие отсчёты, поэтому придётся выбрать какое-то оптимальное окно. В идеале длина окна должна составлять 12600 отсчётов. Просмотреть длину данных в базе и вывести процент, сколько данных меньше определённой длины. Исследуемые длины: 2048, 4096, 8192, 10240, 12600. В дальнейшем мы будем во всех моделях использовать одно и то же окно.

# Замечания на будущее

При обучении необходимо удалять те данные, длина которых меньше длины заданного окна.

**Comment by 13Fire13nyu** [comment]
Проценты для размера окна 2048, 4096, 8192, 10240 и 12600 соответственно:
[0.035707329740959554,
 0.8147763422709863,
 11.348438615854056,
 19.95715120431085,
 41.543855093163664]
Высчитывала по всем данным, а не только по тренировочным.

**Comment by igsha** [comment]
А какое общее количество файлов?

**Comment by 13Fire13nyu** [comment]
30806

**Comment by igsha** [comment]
`30806*0.0357 = 1099` - это для окна 2048. В какой-то из задач Вы говорили, что всего 5 штук.

**Comment by igsha** [comment]
> 

аа, проценты же. Нужно на 100 поделить

**Comment by 13Fire13nyu** [comment]
То было только для тренировочной выборки. Возможно просто так распределились файлы. Они же в рандомном порядке.

**Comment by igsha** [comment]
Поисследуйте этот отрезок: [4096, 8192]. Возьмите в этом отрезке 100 чисели и найдите процент, сколько нужно отбросить из базы. Это потом тоже вставим в диссертацию.

**Comment by 13Fire13nyu** [comment]
Вот список результатов (первое число - размер окна, второе - процент на отбрасывание):
[(4096, 0.8147763422709863),
 (4137, 0.8342530675842369),
 (4178, 0.8504836720119457),
 (4220, 0.8569759137830292),
 (4261, 0.8861910017529053),
 (4302, 0.8991754852950723),
 (4344, 0.934882815036032),
 (4385, 0.9446211776926573),
 (4426, 0.9770823865480751),
 (4468, 0.9998052327468676),
 (4509, 1.0030513536324093),
 (4551, 1.0062974745179512),
 (4592, 1.02252807894566),
 (4633, 1.0614815295721614),
 (4675, 1.1361423099396222),
 (4716, 1.1588651561384147),
 (4757, 1.1848341232227488),
 (4799, 1.2043108485359995),
 (4840, 1.210803090307083),
 (4882, 1.2205414529637084),
 (4923, 1.2335259365058755),
 (4964, 1.2724793871323767),
 (5006, 1.285463870674544),
 (5047, 1.3016944751022528),
 (5088, 1.340647925728754),
 (5130, 1.4704927611504253),
 (5171, 1.5905992339154709),
 (5213, 1.6003375965720963),
 (5254, 1.7042134649094332),
 (5295, 1.75290527819256),
 (5337, 1.7691358826202688),
 (5378, 1.7983509705901446),
 (5419, 1.8178276959033952),
 (5461, 1.8308121794455627),
 (5502, 1.8730117509576056),
 (5544, 3.129260533662274),
 (5585, 3.194182951373109),
 (5626, 3.226644160228527),
 (5668, 3.242874764656236),
 (5709, 3.275335973511653),
 (5750, 3.307797182367071),
 (5792, 3.590209699409206),
 (5833, 3.629163150035707),
 (5875, 3.6551321171200413),
 (5916, 3.9764980847886773),
 (5957, 3.989482568330845),
 (5999, 4.025189898071805),
 (6040, 4.236187755632019),
 (6081, 4.281633448029605),
 (6123, 4.297864052457314),
 (6164, 4.372524832824774),
 (6206, 4.4926313055898195),
 (6247, 4.52833863533078),
 (6288, 4.5510614815295725),
 (6330, 4.6906446796078685),
 (6371, 4.732844251119912),
 (6412, 4.755567097318704),
 (6454, 4.8139972732584555),
 (6495, 4.859442965656041),
 (6537, 4.963318833993378),
 (6578, 5.005518405505421),
 (6619, 5.115886515613841),
 (6661, 5.1515938453548005),
 (6702, 5.187301175095761),
 (6743, 5.206777900409011),
 (6785, 5.5800818022463154),
 (6826, 5.881971044601701),
 (6868, 5.930662857884828),
 (6909, 5.950139583198078),
 (6950, 6.002077517366747),
 (6992, 6.034538726222165),
 (7033, 6.057261572420957),
 (7074, 6.089722781276375),
 (7116, 6.414334869830553),
 (7157, 6.430565474258261),
 (7199, 6.492241771083555),
 (7240, 6.505226254625722),
 (7281, 6.547425826137765),
 (7323, 6.8298383431799),
 (7364, 7.229111212101539),
 (7405, 7.268064662728039),
 (7447, 7.381678893722002),
 (7488, 7.404401739920795),
 (7530, 7.427124586119587),
 (7571, 7.453093553203921),
 (7612, 7.50503148737259),
 (7654, 7.5602155424268),
 (7695, 9.063169512432644),
 (7736, 9.13133805102902),
 (7778, 9.173537622541064),
 (7819, 10.712198922287866),
 (7861, 10.790105823540868),
 (7902, 10.861520483022788),
 (7943, 10.903720054534832),
 (7985, 10.95890410958904),
 (8026, 11.189378692462508),
 (8067, 11.2121015386613),
 (8109, 11.260793351944425),
 (8150, 11.319223527884178),
 (8192, 11.348438615854056)]
​

**Comment by 13Fire13nyu** [comment]
Какой процент в итоге - предельный?

**Comment by igsha** [comment]
Мы можем пожертвовать 1000 файлами. Это соответствует где-то длине окна 5668.
Для окна 8192 получится, что данных для обучения и тестирования всего `30806 * (100-11.35)/100 = 27309`. В принципе, можно и это число взять.

**Comment by 13Fire13nyu** [comment]
> Мы можем пожертвовать 1000 файлами. Это соответствует где-то длине окна 5668. Для окна 8192 получится, что данных для обучения и тестирования всего `30806 * (100-11.35)/100 = 27309`. В принципе, можно и это число взять.

Так даже хорошо, потому что я всё равно количество файлов сокращала до 27000 для удобства разбиения. Но теперь надо понять, какие файлы удалять, потому что раньше разбивались не сами данные, а названия файлов, а считывание данных уже происходило позже.

**Comment by 13Fire13nyu** [comment]
У меня вопрос теперь: все вычисления дальнейшие будут производиться на окне 8192? 2048 больше не рассматривать?

**Comment by igsha** [comment]
> Постройте график, чтобы была видна закономерность.

Жду, для окончательного решения.

**Comment by igsha** [comment]
квадратичный рост. Хорошо, берите 8192 отсчёта.

**Comment by 13Fire13nyu** [comment]
![image](https://user-images.githubusercontent.com/47567199/173059675-08f0833e-d913-4f3e-851d-495985e011ff.png)
