### ISSUE TITLE
Модель MFCC

### ISSUE THREAD

**Issue by igsha** [13Fire13nyu/MasterDegree#21]
# Мотивация

Сделать всё по теории.

# Реалзиация

Посмотреть текущую реализацию и сравнить её с #7.
Подобрать количество спектрограмм в пачке. Остальные параметры уже жёстко задано.

**Comment by igsha** [comment]
Зависит от #20

**Comment by 13Fire13nyu** [comment]
Результаты:
Действия, выполняемые в рамках этой модели, аналогичны действиям для модели STFT. Обучение снова было с предостановкой с задержкой на 10 эпох. Результаты следующие:
![image](https://user-images.githubusercontent.com/47567199/172787611-f30fc963-ac67-479d-8e84-37a0bcffb9b2.png)
Точность - 94.88%. Лучшие параметры - шаг 2048 и 10 спектрограмм.
![image](https://user-images.githubusercontent.com/47567199/172787764-5245512e-e2b0-4c34-b226-69dcc0d1c5c0.png)
![image](https://user-images.githubusercontent.com/47567199/172787811-ffe07f52-cb24-49f0-95ef-ffe8880597b0.png)
![image](https://user-images.githubusercontent.com/47567199/172787832-45427f06-ecec-48ef-aa71-30091393a6c0.png)
Вид спектрограмм:
![image](https://user-images.githubusercontent.com/47567199/172787876-94b715e0-f926-444c-9ac7-faf86cc1ba70.png)
Для 50 эпох:
![image](https://user-images.githubusercontent.com/47567199/172787931-6be1edd6-72d7-41d8-9c16-e209d358fd0f.png)
Точность - 93.70%.

**Comment by 13Fire13nyu** [comment]
Еще из зависимости точности от шага и количества спектрограмм видна интересная зависимость: чем меньше шаг, тем больше надо брать спектрограмм, и наоборот.
