### ISSUE TITLE
Модель STFT

### ISSUE THREAD

**Issue by igsha** [13Fire13nyu/MasterDegree#22]
# Мотивация

Получение шага окна и количества спектрограмм в пачке для модели STFT.

# Реализация

1. Задать шаг `S`
1. Задать размер пачки `P`
1. Преобразование всех данных:
    1. Получить данные из файла `waveform`
        1. Получить пачку спектрограмм `pack = tf.signal.stft(waveform, frame_length=8192, frame_step=S, fft_lenght=8192, pad_end=True)`
        1. Получить мощность спектра `power_pack = tf.abs(pack / np.sqrt(len(pack[0])))**2`
        1. Рандомно вытащить пачку длиной `P` из пачки `power_pack`
        1. Добавить полученную пачку спектрограмм в выборку для обучения `x_train`
1. Запустить обучение модели на полученной выборке `x_train`
1. Запомнить модель, получить метрики
1. Задать новые параметры `S` и `P` и перейти на шаг 3

**Comment by 13Fire13nyu** [comment]
Я заранее генерю списки тренировочными, проверочными и тестовыми данными в соответствии с различными параметрами. К этим спискам я обращаюсь в каждой итерации по параметрам для обучения и получения точности. Модель, историю обучения и точности я тоже сохраняю в списки, чтобы потом иметь возможность к ним обращаться. Но, начиная с 25 спектрограмм при шаге 256, я сталкиваюсь с проблемой нехватки памяти.

**Comment by igsha** [comment]
1. Вместо параметра `validation_data=val_[k]` метода `model.fit` используйте `validation_split`. Не нужно выделать дополнительные массивы
1. В самом начале, когда Вы сделали вот это
    ```
    files_ds = tf.data.Dataset.from_tensor_slices(filenames)
    output_ds = files_ds.map(get_waveform_and_label_check, num_parallel_calls=AUTOTUNE)
    In [9]:
    data = []
    lengths = []
    for a,b,c in output_ds:
        data.append((a.shape[0],b,c))
        lengths.append(a.shape[0])
    ```

    Вы теряете память, потому что переменные нигде не используются, но они всё ещё доступны. Обнулите переменные.
    Ваш датасет состоит из около 27000 файлов, в каждом по 10000 отсчётов примерно. Эти данные вы переводите во `float32`. Получаем `27e3*10e*3/2**30 = 1.006` Гигабайт памяти просто так съедено и лежит без дела.
1. Не нужно готовить данные заранее. Готовьте их в цикле, они Вам больше не понадобятся. Каждая пачка данных съедает примерно по гигу. Вот у Вас и не остаётся памяти.

**Comment by 13Fire13nyu** [comment]
> 

В цикле подготовка данных занимает довольно продолжительное время, поэтому я хотела делать это заранее Можно было бы их как-то в процессе стирать.

**Comment by igsha** [comment]
Можно в файлы их записать. Но это же одно и то же время: что Вы делаете до цикла, что внутри цикла. Или я не прав?
Можете все данные подготовить в отдельно ipynb файле, а потом запомнить полученные массивы. В цикле просто считывать нужные файлы с конкретным массивом.

**Comment by 13Fire13nyu** [comment]
> Можно в файлы их записать. Но это же одно и то же время: что Вы делаете до цикла, что внутри цикла. Или я не прав? Можете все данные подготовить в отдельно ipynb файле, а потом запомнить полученные массивы. В цикле просто считывать нужные файлы с конкретным массивом.

То есть чтение из файла займёт меньше памяти?

**Comment by 13Fire13nyu** [comment]
Результаты:
Мною были рассмотрены варианты шага 256, 512, 1024, 2048, 4096 и 8192, а также количества спектрограмм от 5 до 30 через 5. Обучение проводилось с ранней остановкой с задержкой на 10 итераций при максимальном количестве эпох 300.  Сравнительная карта точностей следующая:
![image](https://user-images.githubusercontent.com/47567199/172729345-bab7a4b8-0b1f-4e7d-953f-404e796df889.png)
Как видно, лучший результат равен 96% и достигается он при шаге 4096 и 20 спектрограммах. Штраф и точность выглядят так:
![image](https://user-images.githubusercontent.com/47567199/172729474-4164d5d6-6ffc-48fb-b78e-d72e9b93b88d.png)
Далее матрица ошибок и тестовое распознавание:
![image](https://user-images.githubusercontent.com/47567199/172729523-5a30298d-acf2-4afd-a361-358208046245.png)
![image](https://user-images.githubusercontent.com/47567199/172729530-b8fe6e69-a2ce-46a2-af6e-44eb9e153b63.png)
Спектрограммы сами имеют следующий вид:
![image](https://user-images.githubusercontent.com/47567199/172729565-6b63c387-ca85-43a3-ab11-a47c47511007.png)
На ней уже явно проявляются артефакты, по которым можно что-то предсказывать.
Итоговое время обучения составило 12 минут 16 секунд

**Comment by 13Fire13nyu** [comment]
Утром скину график штрафа и точности для 50 итераций.

**Comment by 13Fire13nyu** [comment]
![image](https://user-images.githubusercontent.com/47567199/172766944-5d5a434e-50e2-46cd-8088-6c8bc8b30d7e.png)

**Comment by 13Fire13nyu** [comment]
При pad_end = False: Точность - 95.96%, время обучения - 10 минут 55 секунд.
![image](https://user-images.githubusercontent.com/47567199/172951745-77c8a973-ef6c-4011-a848-a8fd1a94cca4.png)
![image](https://user-images.githubusercontent.com/47567199/172951759-f3117e8b-8073-4846-a795-f303ac008435.png)
![image](https://user-images.githubusercontent.com/47567199/172951772-c6725d36-2a98-455d-a665-07b86d162faa.png)
![image](https://user-images.githubusercontent.com/47567199/172951783-6f991b56-7e0f-43f9-85bf-53b66fdf3759.png)
![image](https://user-images.githubusercontent.com/47567199/172951813-a46d6488-a741-429c-af9f-6e54ca4e9367.png)
![image](https://user-images.githubusercontent.com/47567199/172951820-e78eb8a1-04e9-416f-b7c1-2ac78a61589e.png)
Для 50 эпох: точность - 95.11%.
![image](https://user-images.githubusercontent.com/47567199/172951838-38f343a9-156d-4815-b07d-d5fd42e24bed.png)
