### ISSUE TITLE
Результаты исследования

### ISSUE THREAD

**Issue by igsha** [13Fire13nyu/MasterDegree#23]
# Мотивация

Получить таблицу с окончательными результатами, которая пойдёт в диссертацию и презентацию.

# Реализация

Использовать синтаксис таблиц: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables

| Модель | Итоговая точность | Время обучения | Оптимальные параметры | Склонность к переобучению |
|:-----------|:--------:|:----------:|:------------:|:-----------:|
| STFT | | | | сильная/средняя/слабая |
| mDCT | | | | сильная/средняя/слабая |
| MFCC | | | | сильная/средняя/слабая |
| fSTFT | | | | сильная/средняя/слабая |

**Comment by 13Fire13nyu** [comment]
На основе чего я могу судить о склонности к переобучению?

**Comment by 13Fire13nyu** [comment]
| Модель       | Итоговая точность  | Время обучения | Оптимальные параметры | Склонность к переобучению |
| ------------- |:-----------------------:| -------------------:| ------------------------------:| ---------------------------------:|
| STFT            | 95.96%                      | 10 мин 55 сек      | Размер окна: 8192, шаг окна: 2048, количество спектрограмм: 20 | ? |
| MFCC          | centered      |   $12 | 10 мин 55 сек      | Размер окна: 8192, шаг окна: 2048, количество спектрограмм: 20 | ? |
| fSTFT           | are neat      |    $1  | 10 мин 55 сек      | Размер окна: 8192, шаг окна: 2048, количество спектрограмм: 20 | ? |
| mDCT          | are neat      |    $1  | 10 мин 55 сек      | Размер окна: 8192, шаг окна: 2048, количество спектрограмм: 20 | ? |

**Comment by 13Fire13nyu** [comment]
Для выводов о склонности к переобучению я смотрела на графики:
STFT:
![image](https://user-images.githubusercontent.com/47567199/173032521-961ffc21-5b25-4233-bea8-15ac785e77fd.png)
MFCC:
![image](https://user-images.githubusercontent.com/47567199/173032576-175ac67a-b9b5-4455-b8c8-5d83fff1c306.png)
fSTFT:
![image](https://user-images.githubusercontent.com/47567199/173032644-3a726e81-05f2-471f-81ea-5dc2f4a262c8.png)
mDCT:
![image](https://user-images.githubusercontent.com/47567199/173032701-3d08371a-b3af-4f39-975b-82c0fa03ef23.png)

**Comment by igsha** [comment]
Хорошо бы графики проанализировать на 50 эпох. Но так пока тоже сойдёт.
`fSTFT	96.15%	52 сек` - это хороший результат: точность выше всех и обучение самое быстрое. В диссертации и на защите тут нужно отметить, что время обучения не включало предобработку данных. Или время вычислялось вместе с предобработкой?

**Comment by 13Fire13nyu** [comment]
STFT:
![image](https://user-images.githubusercontent.com/47567199/173040991-d7dfee71-9c18-4996-9a29-3e888aede734.png)
MFCC:
![image](https://user-images.githubusercontent.com/47567199/173041038-1a903f38-7088-422c-94fb-69b1c6ea10f8.png)
fSTFT:
![image](https://user-images.githubusercontent.com/47567199/173041106-6e7bbc79-6d67-4b8a-bad0-29be270171bc.png)
mDCT:
![image](https://user-images.githubusercontent.com/47567199/173041177-a213feb8-a3b7-403c-941f-2473ba545d2c.png)

**Comment by 13Fire13nyu** [comment]
| Модель       | Итоговая точность  | Время обучения | Время предобработки | Оптимальные параметры | Склонность к переобучению |
|:-----------|:--------:|:----------:|:------------:|:------------:|:-----------:|
| STFT            | 95.96%                      | 10 мин 55 сек      | 5 сек |Размер окна: 8192, шаг окна: 2048, количество спектрограмм: 20 | Средняя |
| MFCC          | 94.04%                      | 1 мин 18 сек        | 3 сек |Размер окна: 8192, шаг окна: 1024, количество спектрограмм: 15 | Низкая |
| fSTFT           | 96.15%                      |  52 сек                 | 2 сек |Размер окна: 8192, шаг окна: 2048, количество спектрограмм: 25  | Средняя |
| mDCT          | 88.55%                      | 1 мин 20 сек       | 2 сек | Размер окна: 8192, количество спектрограмм: 3 | Высокая |

**Comment by igsha** [comment]
Судя по графику Accuracy, сильное переобучение присутствует у STFT. У mDCT среднее переобучение. Но это мы будем подавать в качестве "субъективной" оценки. Возможно, не стоит вообще это говорить на защите, просто при сравнении моделей видно, что модель MFCC менее всех переобучается.

**Comment by 13Fire13nyu** [comment]
| Модель       | Итоговая точность  | Время обучения | Время предобработки | Оптимальные параметры | Склонность к переобучению |
|:-----------|:--------:|:----------:|:------------:|:------------:|:-----------:|
| STFT            | 95.96%                      | 10 мин 55 сек      | 5 сек |Размер окна: 8192, шаг окна: 2048, количество спектрограмм: 20 | Высокая |
| MFCC          | 94.04%                      | 1 мин 18 сек        | 3 сек |Размер окна: 8192, шаг окна: 1024, количество спектрограмм: 15 | Низкая |
| fSTFT           | 96.15%                      |  52 сек                 | 2 сек |Размер окна: 8192, шаг окна: 2048, количество спектрограмм: 25  | Средняя |
| mDCT          | 88.55%                      | 1 мин 20 сек       | 2 сек | Размер окна: 8192, количество спектрограмм: 3 | Средняя |
