### ISSUE TITLE
Файл для демонстраций

### ISSUE THREAD

**Issue by igsha** [13Fire13nyu/MasterDegree#3]
Найти на просторах интернета wav-файл для полного тестирования сделанной модели. Характеристики wav-файла:
* длительность характиризуется количеством нот в мелодии (должно быть от 50 нот - это около минуты)
* есть разметка по нотам
* присутствует только один инструмент/голос
* выбранный инструмент не должен совпадать с обучающими данными

**Comment by 13Fire13nyu** [comment]
На просторах интернета найти ничего не получилось (либо не очень все же хорошо искала). Сгенерировала небольшую запись с гитарой, там больше 60 нот, но это не минута, а 29 секунд. Разметку сделала тоже: время брала в программе, где генерировала мелодию (fl studio 20, конкретнее в патче edison), высоту тона извлекла из файла midi (соответствие нотам проверила с помощью функции, которую писала ранее при разбиении датасетов на ноты). Могу все это залить в гитхаб.

**Comment by igsha** [comment]
Звук слишком чистый. Нельзя какой-то шум наложить?

**Comment by 13Fire13nyu** [comment]
Посмотрю, что с этим можно сделать

**Comment by 13Fire13nyu** [comment]
Немного подкорректировала запись (пока таблицу не правила): https://drive.google.com/drive/folders/1P-9DzPUmHa7f_TRcvajbqAiqSVI2Y0Qy?usp=sharing

**Comment by igsha** [comment]
Ладно, пока будем на этом тестироваться.
