### ISSUE TITLE
Определение размеров входных данных для нейросети

### ISSUE THREAD

**Issue by igsha** [13Fire13nyu/MasterDegree#5]
На вход нейросети подаются данные всегда одной и той же размерности. Необходимо определится с размерностями этих данных.
1. Подавать моно-сигнал.
2. Так как человеческое ухо не слышит колебания меньше 20 Гц, то эта граница для нас будет задавать максимальный размер окна. Для частоты дискретизации 44100 отсчётов/сек. получаем `44100 / 20 = 2205`. Для красоты возьмём 2048 отсчётов (21.5 Гц) - это и будет **размером фрейма** для оконного преобразования Фурье. Длительность 2048 отсчётов составляет примерно 0.046 сек. звука.
3. Шаг смещения фрейма взять в половину отсчётов.
4. После оконного преобразования Фурье получаем множество коротких спектров длиной 1024 отсчёта - это и будем называть одной спектрограммой, которая определяет текущий спектр звука длительностью 0.046 сек.
5. На вход нейросети подаётся несколько соседних спектрограмм. Будем брать как в той статье-диссертации: 15 последовательных спектрограмм. Это будет соответствовать примерно 0.7 сек. анализируемого звука  с цетром в 8 спектрограмме.
6. В итоге получим размерность входа для нейросетевой модели: 1024x15 = 15360.

Переделать входные данные описанным выше способом. Проверка: при распечатывании модели, входной слой должен иметь размерность 1024x15 (либо наоборот, зависит от представления данных).

**Comment by 13Fire13nyu** [comment]
> На вход нейросети подаются данные всегда одной и той же размерности. Необходимо определится с размерностями этих данных.
> 
> 1. Подавать моно-сигнал.
> 2. Так как человеческое ухо не слышит колебания меньше 20 Гц, то эта граница для нас будет задавать максимальный размер окна. Для частоты дискретизации 44100 отсчётов/сек. получаем `44100 / 20 = 2205`. Для красоты возьмём 2048 отсчётов (21.5 Гц) - это и будет **размером фрейма** для оконного преобразования Фурье. Длительность 2048 отсчётов составляет примерно 0.046 сек. звука.
> 3. Шаг смещения фрейма взять в половину отсчётов.
> 4. После оконного преобразования Фурье получаем множество коротких спектров длиной 1024 отсчёта - это и будем называть одной спектрограммой, которая определяет текущий спектр звука длительностью 0.046 сек.
> 5. На вход нейросети подаётся несколько соседних спектрограмм. Будем брать как в той статье-диссертации: 15 последовательных спектрограмм. Это будет соответствовать примерно 0.7 сек. анализируемого звука  с цетром в 8 спектрограмме.
> 6. В итоге получим размерность входа для нейросетевой модели: 1024x15 = 15360.
> 
> Переделать входные данные описанным выше способом. Проверка: при распечатывании модели, входной слой должен иметь размерность 1024x15 (либо наоборот, зависит от представления данных).

Добавила код Data_fitting_v2.ipynb с заданными изменениями.

**Comment by igsha** [comment]
Давайте добавлять не нули, делать дублирование последних полосок спектрограмм. То есть, по длине файлов получили спектрограмму `(N, 1025)`, при это `N < 15`. Далее доводим массив до вида `(15, 1025)`, путём копирования элемента `N-1`.

И сделайте выделение `1025x15`, а не `1024x15`.

**Comment by 13Fire13nyu** [comment]
> Давайте добавлять не нули, делать дублирование последних полосок спектрограмм. То есть, по длине файлов получили спектрограмму `(N, 1025)`, при это `N < 15`. Далее доводим массив до вида `(15, 1025)`, путём копирования элемента `N-1`.
> 
> И сделайте выделение `1025x15`, а не `1024x15`.

Имеется в виду здесь поменять input_length?
![image](https://user-images.githubusercontent.com/47567199/166095634-9b92b9e5-f7b3-4c09-8f0c-778ced907f71.png)

**Comment by 13Fire13nyu** [comment]
> 

Столкнулась с проблемой следующего рода:
![image](https://user-images.githubusercontent.com/47567199/166105015-5b19b3d5-1aa9-4fd9-9fb3-06217922d169.png)
Из-за этого получаю ошибку, поскольку мой код дополнения спектрограммы до формы (15, 1025) основывался на spectrogram.shape[0]. Код с ошибкой скинула в гитхаб в  Data_fitting_v2.ipynb

**Comment by 13Fire13nyu** [comment]
> > 
> 
> Столкнулась с проблемой следующего рода: ![image](https://user-images.githubusercontent.com/47567199/166105015-5b19b3d5-1aa9-4fd9-9fb3-06217922d169.png) Из-за этого получаю ошибку, поскольку мой код дополнения спектрограммы до формы (15, 1025) основывался на spectrogram.shape[0]. Код с ошибкой скинула в гитхаб в Data_fitting_v2.ipynb

**Comment by 13Fire13nyu** [comment]
> Давайте добавлять не нули, делать дублирование последних полосок спектрограмм. То есть, по длине файлов получили спектрограмму `(N, 1025)`, при это `N < 15`. Далее доводим массив до вида `(15, 1025)`, путём копирования элемента `N-1`.
> 
> И сделайте выделение `1025x15`, а не `1024x15`.

В общем, ситуация обстоит следующим образом. Я попыталась дополнить спектрограммы с помощью лямбда-функции в map, поскольку спектрограммы с метками хранятся в tf.data.Dataset. Другого способа добраться к длине спектрограммы я найти не смогла. Однако, далеко не все спектрограммы поддались такой махинации. Я попробовала использовать эту лямбда-функцию дважды, и количество не приведенных к нужной длине спектрограмм подсократилось, но все равно остались спектрограммы с меньшей длиной. Да и такой способ решения проблемы мне не кажется разумным. Также попутно я выяснила, что есть такие сигналы, длина которых равна внезапно 0, отчего и спектрограммы их нулевые. Номера таких сигналов в текущем порядке я вывела на изображении:
![image](https://user-images.githubusercontent.com/47567199/166124217-50c2b45d-d147-4c26-8698-6541a3234edc.png)
Отсюда вопрос: что с этим всем делать?

**Comment by igsha** [comment]
Но почему образовались нулевой длины данные? Может файлы какие-то не скачались?

Можете воспользоваться интрерфейсом `model.fit`, который использует параметры `x` и `y`, а не датасет: https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit. Параметр `validation_data` при этом будет выглядет как `validation_data=(val_x, val_y)`. В таком интерфейсе спектрограммы нужно подготовить заранее и можно будет повыводить их, чтобы понять, где какие размерности не сходятся.

**Comment by 13Fire13nyu** [comment]
> Но почему образовались нулевой длины данные? Может файлы какие-то не скачались?
> 
> Можете воспользоваться интрерфейсом `model.fit`, который использует параметры `x` и `y`, а не датасет: https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit. Параметр `validation_data` при этом будет выглядет как `validation_data=(val_x, val_y)`. В таком интерфейсе спектрограммы нужно подготовить заранее и можно будет повыводить их, чтобы понять, где какие размерности не сходятся.

По поводу нулевых сигналов - возможно, там были настолько короткие сигналы, что они получились нулевой длины. С подготовкой спектрограмм -  это значит их надо куда-то заранее сохранить?

**Comment by 13Fire13nyu** [comment]
> Но почему образовались нулевой длины данные? Может файлы какие-то не скачались?
> 
> Можете воспользоваться интрерфейсом `model.fit`, который использует параметры `x` и `y`, а не датасет: https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit. Параметр `validation_data` при этом будет выглядет как `validation_data=(val_x, val_y)`. В таком интерфейсе спектрограммы нужно подготовить заранее и можно будет повыводить их, чтобы понять, где какие размерности не сходятся.

Я посмотрела файлы, которые код принял за файлы нулевой длины, не похоже, чтобы они реально были нулевыми. Видимо, они действительно почему-то не прочитываются.

**Comment by 13Fire13nyu** [comment]
> Но почему образовались нулевой длины данные? Может файлы какие-то не скачались?
> 
> Можете воспользоваться интрерфейсом `model.fit`, который использует параметры `x` и `y`, а не датасет: https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit. Параметр `validation_data` при этом будет выглядет как `validation_data=(val_x, val_y)`. В таком интерфейсе спектрограммы нужно подготовить заранее и можно будет повыводить их, чтобы понять, где какие размерности не сходятся.

В каком формате должны быть x, y, val_x и val_y?

**Comment by 13Fire13nyu** [comment]
> Но почему образовались нулевой длины данные? Может файлы какие-то не скачались?
> 
> Можете воспользоваться интрерфейсом `model.fit`, который использует параметры `x` и `y`, а не датасет: https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit. Параметр `validation_data` при этом будет выглядет как `validation_data=(val_x, val_y)`. В таком интерфейсе спектрограммы нужно подготовить заранее и можно будет повыводить их, чтобы понять, где какие размерности не сходятся.

В общем, я просто добавила фильтрацию от нулевых сигналов в проверочный и тестовый наборы, и все заработало. Код скинула.

**Comment by igsha** [comment]
Хорошо, переходите тогда снова к #4.
Всё-таки, 1024x15 было правильнее. Насколько я понял, сейчас это ни на что не влияет.

**Comment by 13Fire13nyu** [comment]
[Код с обучением](https://github.com/13Fire13nyu/MasterDegree/blob/master/Data_fitting_v2.ipynb), [Код демо](https://github.com/13Fire13nyu/MasterDegree/blob/master/demo_v2.ipynb)
