### ISSUE TITLE
Cпектрограмма

### ISSUE THREAD

**Issue by igsha** [13Fire13nyu/MasterDegree#6]
Задание делать после готовности #5 и #7.

Необходимо реализовать спектрограмму по правильному алгоритму. Старый код не удаляем, просто добавляем ещё один. На этом этапе нужно сравнить результаты.

1. Возвести полученные спектрограммы в квадрат и поделить на количество отсчётов в спектре (можно ещё на 2 поделить, но это вообще не важно, так как все фреймы были одинаковыми).
1. Применить трангулярные фильтры из #7.
1. От полученных отсчётов берём логарифм и получаем кепстр.
1. Размер уже полученной спектрограммы должен быть меньше оригинальной.
1. Выписать сюда полученную форму новой спектрограммы.

При написании использовал статью http://practicalcryptography.com/miscellaneous/machine-learning/guide-mel-frequency-cepstral-coefficients-mfccs/

**Comment by 13Fire13nyu** [comment]
> Задание делать после готовности #5 и #7.
> 
> Необходимо реализовать спектрограмму по правильному алгоритму. Старый код не удаляем, просто добавляем ещё один. На этом этапе нужно сравнить результаты.
> 
> 1. Возвести полученные спектрограммы в квадрат и поделить на количество отсчётов в спектре (можно ещё на 2 поделить, но это вообще не важно, так как все фреймы были одинаковыми).
> 2. Применить трангулярные фильтры из [Подготовка триангулярных фильтров #7](https://github.com/13Fire13nyu/MasterDegree/issues/7).
> 3. От полученных отсчётов берём логарифм и получаем кепстр.
> 4. Размер уже полученной спектрограммы должен быть меньше оригинальной.
> 5. Выписать сюда полученную форму новой спектрограммы.
> 
> При написании использовал статью http://practicalcryptography.com/miscellaneous/machine-learning/guide-mel-frequency-cepstral-coefficients-mfccs/

Залила код с реализацией получения спектрограммы для одного примера записи: [код](https://github.com/13Fire13nyu/MasterDegree/blob/master/Spectrogram_and_filterbanks.ipynb). Но в статье-методичке, по которой я делала этот код ([статья](https://russianblogs.com/article/18381249121/)), некоторые параметры задавались с учетом того, что стояла задача распознавания речи: num_ceps = 12 в пункте "Мел-частотные кепстральные коэффициенты (MFCC)", cep_lifter = 22 - стоит как значение по умолчанию (вычитала из комментариев к статье-источнику самой статьи). Мне надо как-то менять эти параметры?
Форма полученной спектрограммы: filter_banks.shape = (42, 40); Форма mfcc: mfcc.shape = (42, 12).

**Comment by igsha** [comment]
Давайте не торопиться и вводить улучшения постепенно.

* Получение спектрограммы должно быть через вызов функции `tf.signal.stft`. Не нужно накладывать какие-то окна, это делает сам `stft`
* Разбивать на фреймы и дополнять нулями не нужно, это делает сам `stft`
* После вычисления мощности спектра, сравните полученную величину с мощностью сигнала. Нам нужно, чтобы они примерно совпадали (по равенству Парсеваля), чтобы понять, нужно ли делить на количество отсчётов.
* Фильтры загрузите через `np.load`. Код копировать сюда не нужно
* После получения кепстра ничего делать не нужно. У Вас получилась каша сейчас, потому что после преобразования Фурье Вы берёте косинусное преобразование от кепстра. Это масло масленое. Нужно либо Фурье брать, либо косинусное. Мы сейчас будем использовать только оконное преобразование Фурье через `stft`.

**Comment by 13Fire13nyu** [comment]
> Давайте не торопиться и вводить улучшения постепенно.
> 
> * Получение спектрограммы должно быть через вызов функции `tf.signal.stft`. Не нужно накладывать какие-то окна, это делает сам `stft`
> * Разбивать на фреймы и дополнять нулями не нужно, это делает сам `stft`
> * После вычисления мощности спектра, сравните полученную величину с мощностью сигнала. Нам нужно, чтобы они примерно совпадали (по равенству Парсеваля), чтобы понять, нужно ли делить на количество отсчётов.
> * Фильтры загрузите через `np.load`. Код копировать сюда не нужно
> * После получения кепстра ничего делать не нужно. У Вас получилась каша сейчас, потому что после преобразования Фурье Вы берёте косинусное преобразование от кепстра. Это масло масленое. Нужно либо Фурье брать, либо косинусное. Мы сейчас будем использовать только оконное преобразование Фурье через `stft`.

Хорошо, буду работать.

**Comment by 13Fire13nyu** [comment]
> Давайте не торопиться и вводить улучшения постепенно.
> 
> * Получение спектрограммы должно быть через вызов функции `tf.signal.stft`. Не нужно накладывать какие-то окна, это делает сам `stft`
> * Разбивать на фреймы и дополнять нулями не нужно, это делает сам `stft`
> * После вычисления мощности спектра, сравните полученную величину с мощностью сигнала. Нам нужно, чтобы они примерно совпадали (по равенству Парсеваля), чтобы понять, нужно ли делить на количество отсчётов.
> * Фильтры загрузите через `np.load`. Код копировать сюда не нужно
> * После получения кепстра ничего делать не нужно. У Вас получилась каша сейчас, потому что после преобразования Фурье Вы берёте косинусное преобразование от кепстра. Это масло масленое. Нужно либо Фурье брать, либо косинусное. Мы сейчас будем использовать только оконное преобразование Фурье через `stft`.

Я правильно понимаю, что сумма квадратов модулей отсчетов сигнала должна быть примерно равна сумме квадратов модулей отсчетов спектра, полученного с помощью `tf.signal.stft`? Потому что если это так, то я бы не сказала, что там есть какое-то совпадение (это для сигнала, который я рассматривала в коде):
![image](https://user-images.githubusercontent.com/47567199/167178320-bbd321eb-ac2f-4fe2-8175-56eedffddb7c.png)

**Comment by igsha** [comment]
Нужно посчитать только одно окно:
```python
print(np.linalg.norm(mag_frames, axis=1))
print(np.linalg.norm(waveform[:2048]))
```

**Comment by 13Fire13nyu** [comment]
> 

Для mag_frames выводится массив значений, а для waveform - одно число:
[7131643.  7050629.5 6692096.5 6576013.  6525913.  6624305.  6327345.5
 6113035.5 6169429.  6383412.5 6652691.  6654082.  6546976.  6341753.
 6130795.  6113870.5 6407983.5 6625130.  6610011.5 6451804.  6514191.5
 6568077.  6497459.5 6512391.  6507535.5 6473901.5 6312136.5 6288023.5
 6231054.5 6309351.  6423658.5 6507021.5 6367749.  6164429.  6061403.
 6201472.5 6544346.5 6684783.5 6808587.  6796568.5 6646046.  6513565.5
 5901635.5 1441128. ]
357801.16

**Comment by igsha** [comment]
`7131643 / 357801.16 ≈ 19.93` - это значит, что энергия спектрограммы больше примерно в 19 раз. Хорошо бы проверить для всех значений.

**Comment by 13Fire13nyu** [comment]
Я рассмотрела разницу мощностей для всех фреймов, почти везде (исключение - 2 последних кадра) разница равна примерно в 19 раз ([код](https://github.com/13Fire13nyu/MasterDegree/blob/master/Spectrogram_and_filterbanks.ipynb)). С добавлением фильтров в старый код возникли затруднения:
![image](https://user-images.githubusercontent.com/47567199/167924778-13261600-219e-42e3-b971-25285075631b.png)
![image](https://user-images.githubusercontent.com/47567199/167924848-e28bd369-b66e-4e04-b851-daea28dec44f.png)
Вот код: [код](https://github.com/13Fire13nyu/MasterDegree/blob/master/Data_fitting_v3.ipynb)

**Comment by igsha** [comment]
> С добавлением фильтров в старый код возникли затруднения:

Ошибка в этой строке:
```python
filter_banks = np.dot(pow_frames, fbank.T)
```
Если перевести с английского, то операция `np.dot` не подходит для тензоров. Нужно использовать аналогичную функцию из tensorflow.

**Comment by 13Fire13nyu** [comment]
> > С добавлением фильтров в старый код возникли затруднения:
> 
> Ошибка в этой строке:
> 
> ```python
> filter_banks = np.dot(pow_frames, fbank.T)
> ```
> 
> Если перевести с английского, то операция `np.dot` не подходит для тензоров. Нужно использовать аналогичную функцию из tensorflow.

Я пыталась использовать tf.tensordot, но возникли какие-то проблемы с типами

**Comment by igsha** [comment]
Необходимо `fbank.T` перевести изначально в тензоры с помощью https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor

**Comment by 13Fire13nyu** [comment]
> Необходимо `fbank.T` перевести изначально в тензоры с помощью https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor

Все еще возникает ошибка, пусть и немного уже иная:
![image](https://user-images.githubusercontent.com/47567199/168120535-d2dc44f1-7059-4852-8af6-a9a64065126e.png)
При загрузке фильтров сразу их конвертирую в тензор:
`# Загружаем триангулярные фильтры
with open('filters.npy', 'rb') as f:
    fbank = np.load(f)
    
fbank = tf.convert_to_tensor(fbank.T, dtype=tf.float32)    `
Вместо np.dot использую tf.tensordot:
` filter_banks = tf.tensordot(pow_frames, fbank, axes = 1)`
Возможно здесь дело в символическом тензоре, который подается на вход функции получения спектрограммы? Она может возникнуть, поскольку мы работаем с датасетом:
`spectrogram_ds = waveform_ds.map(map_func=get_spectrogram_and_label_id, num_parallel_calls=AUTOTUNE)
`
Но тогда у меня пока нет идей, как такое исправить.

**Comment by 13Fire13nyu** [comment]
Попробовала решить проблему вот так:
```
filter_banks = tf.tensordot(pow_frames, fbank, axes = 1)
filter_banks = tf.where(filter_banks == 0, tf.keras.backend.epsilon(), filter_banks)  # Численная стабильность 
# (np.finfo(float).eps - машинный ноль)
spectrogram = tf.math.log(filter_banks)  # Логарифмические энергии набора фильтров
```
Программа посчиталась, но уже при построении примеров спектрограмм возникла новая ошибка:
```
rows = 3
cols = 3
n = rows*cols
fig, axes = plt.subplots(rows, cols, figsize=(10, 10))
for i, (spectrogram, label_id) in enumerate(spectrogram_ds.take(n)):
    print(spectrogram)
```
![image](https://user-images.githubusercontent.com/47567199/168123708-8bac9dc2-ca2a-473d-a81b-e2e94295dfd1.png)

![image](https://user-images.githubusercontent.com/47567199/168123553-9a7e2a08-281d-4c8c-9439-86a7dcd02420.png)

**Comment by 13Fire13nyu** [comment]
Заменила параметр `axes` внутри `tf.tensordot`:
`filter_banks = tf.tensordot(pow_frames, fbank, axes = [[1], [0]])`
После этого весь код заработал, но точности понизилась (примерно 82%). Код обновила: [код](https://github.com/13Fire13nyu/MasterDegree/blob/master/Data_fitting_v3.ipynb)

**Comment by igsha** [comment]
* `filter_banks = tf.tensordot(pow_frames, fbank, axes = [[1], [0]])` - выведите размерности `pow_frames` и `fbank`. Должно быть нормальное умножение матриц
* В модели используется входная размерность `inputs (InputLayer)         [(None, 15, 40, 1)] `. Необходимо добиться, чтобы была входная размерность ` [(None, 15, 40)] `. Нам не нужны посторонние размерности. Скорее всего где-то вручную добавляется ещё одна размерность
* `Epoch 7: early stopping` - надо посмотреть больше эпох. Отключите раннюю остановку и рассмотрите 100 эпох (где-то 3-4 минуты) будет идти обучение

**Comment by igsha** [comment]
> `pow_frames.shape = (None, 1025)`

Это нормально. Тензорфлоу всё вычисляет отложенно, когда размерности ещё не все известны.

Для этой задачи результаты подойдут.
