### ISSUE TITLE
Подготовка триангулярных фильтров

### ISSUE THREAD

**Issue by igsha** [13Fire13nyu/MasterDegree#7]
См. https://russianblogs.com/article/18381249121/

* У нас `sample_rate` составляет 44100 Гц
* Минимальная частоту взять равной 21.5 Гц (или более точно 44100 / 2048)
* Количество фильтров составлять для начала 40
* Построить графики фильтров на одном плоте
* Прикрепить к этому заданию полученные графики

**Comment by 13Fire13nyu** [comment]
Не понимаю, по каким данным в пункте Filter Banks строят следующую спектрограмму:
![image](https://user-images.githubusercontent.com/47567199/166278110-41022a02-485b-4c51-9288-d6e9a9f52985.png)

**Comment by 13Fire13nyu** [comment]
Немного почитала статью, на которую делается ссылка при вводе формулы для банков фильтров. Пока имею следующий результат:
![image](https://user-images.githubusercontent.com/47567199/166294362-089eff80-afa7-4a3e-84fe-0f83faaae20d.png)

**Comment by igsha** [comment]
> и как была построена спектрограмма, показанная в пункте Filter Banks.

Это спектрограмма сигнала, к которому применён Filter Banks, а не спектрограмма Filter Banks.

Соответсвующий код присутствует в репозитории?

**Comment by 13Fire13nyu** [comment]
> > и как была построена спектрограмма, показанная в пункте Filter Banks.
> 
> Это спектрограмма сигнала, к которому применён Filter Banks, а не спектрограмма Filter Banks.
> 
> Соответсвующий код присутствует в репозитории?

Пока ещё не кидала этот код, вечером скину. И что по поводу пункта "Демонстрационный пример"?

**Comment by 13Fire13nyu** [comment]
> > > и как была построена спектрограмма, показанная в пункте Filter Banks.
> > 
> > 
> > Это спектрограмма сигнала, к которому применён Filter Banks, а не спектрограмма Filter Banks.
> > Соответсвующий код присутствует в репозитории?
> 
> Пока ещё не кидала этот код, вечером скину. И что по поводу пункта "Демонстрационный пример"?

Код прикрепила.

**Comment by igsha** [comment]
Почему `NFFT` равняется 512? Должно быть 2048, потому что у нас длина окна именно такая. Всё, что выше заголовка `Банки фильтров`, делается в `tf.signal.stft` и не подходит для этого задания. Здесь только нужно сгенерировать банки фильтров.

**Comment by igsha** [comment]
Сохраните синтезированные фильтры:
```python
with open('filters.npy', 'wb') as f:
    np.save(f, fbank)
```

При подготовке спектра просто загрузите фильтры:
```python
with open('filters.npy', 'rb') as f:
    fbank = np.load(f)
```

**Comment by 13Fire13nyu** [comment]
[Код](https://github.com/13Fire13nyu/MasterDegree/blob/master/filterbanks.ipynb)
