### ISSUE TITLE
Применения

### ISSUE THREAD

**Issue by igsha** [13Fire13nyu/MasterDegree#8]
Придумать и выписать в это задание применения метода гармонического анализа с помощью нейронных сетей (нужно привести несколько). Оценить производительность метода, чтобы можно было показать, что система распознавания работает очень быстро.
Про применения будут спрашивать на защите, поэтому нужно подготовиться заранее.

**Comment by 13Fire13nyu** [comment]
Вот несколько применений, которые я пока нашла
1.	Микролокальный анализ для извлечения наборов цифровых волновых фронтов (пример: поиск опухоли на изображении по форме и расположению) (https://epubs.siam.org/doi/abs/10.1137/19M1237594);
2.	Дистанционно зондируемая оценка общего содержания железа в почве (https://plantmethods.biomedcentral.com/articles/10.1186/s13007-021-00812-8);
3.	Сканирование деятельности головного мозга с помощью миниатюрных устройств для принятия решения о необходимости медицинского вмешательства, стимуляции, нейронного отклика и так далее (https://nplus1.ru/material/2017/05/23/nathan-intrator-1);

Применение в музыке
1.	Теоретический анализ:
1.1.	Вычислительный гармонический анализ музыки;
1.2.	Автоматический анализ отклонения от правил построения музыки композитором в плане использования инструментов и методов;
2.	Коммерческие приложения
2.1.	Программы обучения музыке; 
2.2.	Генераторы лид-листов;
3.	Задачи более высокого уровня:
3.1.	Идентификация кавер-версии;
3.2.	Классификация ключей.
4.	Эффективное получение хороших аппроксимаций некоторых видов многомерных функций.
Источники:
4.	https://www.wjamesmaclean.net/Grads/Tsui_MASc.pdf
5.	file:///D:/magistracy/diplom/dissertation.pdf
6.	http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.162.1505&rep=rep1&type=pdf
7.	https://www.birs.ca/cmo-workshops/2016/16w5136/report16w5136.pdf

**Comment by igsha** [comment]
> 4. Эффективное получение хороших аппроксимаций некоторых видов многомерных функций.

Как это? Поподробнее.

> 2.2. Генераторы лид-листов;

Что это значит?

> 3.2. Классификация ключей.

Имеется в виду мызыкальные ключи? Как это можно сделать?

---

По всем пунктам Вам нужно чётко понимать как это можно сделать, имея только свои наработки. Сейчас мы можем определять основную гармонику одноинструментального звука (без других инструментов) без определения октав.

**Comment by 13Fire13nyu** [comment]
> > 4. Эффективное получение хороших аппроксимаций некоторых видов многомерных функций.
> 
> Как это? Поподробнее.
> 
> > 2.2. Генераторы лид-листов;
> 
> Что это значит?
> 
> > 3.2. Классификация ключей.
> 
> Имеется в виду мызыкальные ключи? Как это можно сделать?
> 
> По всем пунктам Вам нужно чётко понимать как это можно сделать, имея только свои наработки. Сейчас мы можем определять основную гармонику одноинструментального звука (без других инструментов) без определения октав.

Я пока искала применения метода гармонического анализа с помощью нейронных сетей в принципе. Точно сказать как переводится выражение lead sheets я не могу.

**Comment by 13Fire13nyu** [comment]
По поводу применения имеющихся наработок мне в голову пришла пара идей: 
1. Аудиопоисковые системы (поиск песен по главной мелодии, здесь идет сопоставление акапельного пения с фрагментами оригинальной записи);
2. Генерация мелодии, исполняемой необходимым инструментом, на основе акапельного исполнения/исполнения другим инструментом.
Конечно, в дальнейшем эти наработки можно расширять в направлении распознавания октав или аккордов.

**Comment by igsha** [comment]
> По поводу применения имеющихся наработок мне в голову пришла пара идей:
> 
> 1. Аудиопоисковые системы (поиск песен по главной мелодии, здесь идет сопоставление, например, акапельного пения с фрагментами оригинальной записи);
> 2. Генерация мелодии, исполняемой необходимым инструментом, на основе акапельного исполнения/исполнения другим инструментом.
> 
> Конечно, в дальнейшем эти наработки можно расширять в направлении распознавания октав и аккордов.

Да, это хорошо подходит. Надо ещё найти что-то про применения в какой-то несмежной области. Например в экономике. По-моему, анализ тренда рынка делают с помощью поиска основной гармоники кривой тренда.

**Comment by 13Fire13nyu** [comment]
Нашла статью об использовании гармонического анализа для прогнозирования продаж: https://eduherald.ru/ru/article/view?id=15861. Там пытались смоделировать циклы колебаний продаж препаратов, чтобы отслеживать периоды заболеваемости для оценки объема закупок, будущую прибыль и периоды, в которые следует усилить меры борьбы с вирусными заболеваниями. Такой пример подходит?

**Comment by 13Fire13nyu** [comment]
Еще нашла такую штуку, которая называется тканевой гармоники. Это из медицины. Но не знаю, то ли это.

**Comment by igsha** [comment]
> тканевой гармоники.

https://www.usclub.ru/glossary/item/tkanevaya-garmonika--thi---tissue-harmonic-imaging- - да, вроде бы отдалённо подходит.

Остальные тоже подходят. На этом задачу считаем закрытой.
