### ISSUE TITLE
Визуализация спектрограмм

### ISSUE THREAD

**Issue by igsha** [13Fire13nyu/MasterDegree#9]
Спектрограммы кажутся транспонированны:

![image](https://user-images.githubusercontent.com/5345170/168422145-d7516c30-b1c6-45c6-a03f-6569e582fea4.png)

Должно быть:
* по оси X номер спектрограммы (их 15 штук)
* по оси Y номер фильтра (их должно быть 40)

Для модели иметь размерность `(15, 40)` - это хорошо, но для визуализации следует транспонировать спектрограмму.
Также подпишите оси, иначе сразу непонятно, где спектрограмма, а где номер фрейма.

**Comment by 13Fire13nyu** [comment]
![image](https://user-images.githubusercontent.com/47567199/168480061-010b8b12-d5b1-420d-af00-af4a5287f00b.png)

**Comment by igsha** [comment]
На картинках всё хорошо теперь. Поправьте это в коде.

**Comment by 13Fire13nyu** [comment]
[код](https://github.com/13Fire13nyu/MasterDegree/blob/master/Data_fitting_v3.ipynb)
